import React, { Component } from 'react';
import './App.css';
import ProductList from './ProductList';
import SelectedProduct from './SelectedProduct';

// This access key is registered for the domain github.com
// Also attempted with new key on codepen
const ACCESS_KEY = 'MDo0NTllYzdlYy1jNzc0LTExZTgtYTc1YS1jN2NjNTYwZWNhOTA6WGEzSDdhS2xqbW1wc05ERjE1MFBZMUg2Ykw5SUpnMEpDMEFl';
const PRODUCTS_URL = 'https://lcboapi.com/products/?q=beau%27s+all+natural+brewing';
// const PRODUCTS_URL = 'https://lcboapi.com/products?access_key=' + ACCESS_KEY;
// const PRODUCTS_URL = 'https://lcboapi.com/products/?q=beau%27s+all+natural+brewing?access_key=' + ACCESS_KEY;
// const PRODUCTS_URL = 'https://lcboapi.com/products?access_key=' + ACCESS_KEY + '/?q=beau%27s+all+natural+brewing';

const STORES_URL = 'https://lcboapi.com/stores?product_id=';

const HEADERS = {
  mode: 'no-cors',
  header: {
    'Access-Control-Allow-Origin': '*',
    'Authorization': 'Token token='+ ACCESS_KEY,
    'Content-Type': 'application/json'
  }
};

// this const is the results data returned from http://lcboapi.com/products/?q=beau%27s+all+natural+brewing
// CORS and/or CORB errors
// collapse this array while viewing

const products = [
    {
        "id": 169334,
        "is_dead": false,
        "name": "Beau's Lug Tread Lagered Ale",
        "tags": "beau's beaus lug tread lagered ale beer hybrid canada ontario all natural brewing bottle",
        "is_discontinued": false,
        "price_in_cents": 1695,
        "regular_price_in_cents": 1695,
        "limited_time_offer_savings_in_cents": 0,
        "limited_time_offer_ends_on": null,
        "bonus_reward_miles": 0,
        "bonus_reward_miles_ends_on": null,
        "stock_type": "LCBO",
        "primary_category": "Beer",
        "secondary_category": "Hybrid",
        "origin": "Canada, Ontario",
        "package": "4x600 mL bottle",
        "package_unit_type": "bottle",
        "package_unit_volume_in_milliliters": 600,
        "total_package_units": 4,
        "volume_in_milliliters": 2400,
        "alcohol_content": 520,
        "price_per_liter_of_alcohol_in_cents": 1358,
        "price_per_liter_in_cents": 706,
        "inventory_count": 10315,
        "inventory_volume_in_milliliters": 24756000,
        "inventory_price_in_cents": 17483925,
        "sugar_content": null,
        "producer_name": "Beau's All Natural Brewing",
        "released_on": "2012-05-11",
        "has_value_added_promotion": false,
        "has_limited_time_offer": false,
        "has_bonus_reward_miles": false,
        "is_seasonal": false,
        "is_vqa": false,
        "is_ocb": true,
        "is_kosher": false,
        "value_added_promotion_description": null,
        "description": null,
        "serving_suggestion": null,
        "tasting_note": "Golden yellow colour with a thick head; aromas of fragant hops, citrus and roasted malt with yeasty tones; dryish, medium bodied, fresh, smooth and creamy, with forward hop and grain/cereal flavours; crisp and refreshing on the finish.",
        "updated_at": "2018-10-04T14:18:22.168Z",
        "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/169334/images/thumb.png",
        "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/169334/images/full.jpeg",
        "varietal": "Kolsch",
        "style": "Medium & Malty",
        "tertiary_category": "Pale Hybrid Beer",
        "sugar_in_grams_per_liter": null,
        "clearance_sale_savings_in_cents": 0,
        "has_clearance_sale": false,
        "product_no": 169334
    },
    {
        "id": 517797,
        "is_dead": false,
        "name": "Beau's Lug Tread",
        "tags": "beau's beaus lug tread beer hybrid canada ontario all natural brewing can",
        "is_discontinued": false,
        "price_in_cents": 994,
        "regular_price_in_cents": 994,
        "limited_time_offer_savings_in_cents": 0,
        "limited_time_offer_ends_on": null,
        "bonus_reward_miles": 0,
        "bonus_reward_miles_ends_on": null,
        "stock_type": "LCBO",
        "primary_category": "Beer",
        "secondary_category": "Hybrid",
        "origin": "Canada, Ontario",
        "package": "4x355 mL can",
        "package_unit_type": "can",
        "package_unit_volume_in_milliliters": 355,
        "total_package_units": 4,
        "volume_in_milliliters": 1420,
        "alcohol_content": 520,
        "price_per_liter_of_alcohol_in_cents": 1346,
        "price_per_liter_in_cents": 700,
        "inventory_count": 14681,
        "inventory_volume_in_milliliters": 20847020,
        "inventory_price_in_cents": 14592914,
        "sugar_content": null,
        "producer_name": "Beau's All Natural Brewing",
        "released_on": "2012-05-11",
        "has_value_added_promotion": false,
        "has_limited_time_offer": false,
        "has_bonus_reward_miles": false,
        "is_seasonal": false,
        "is_vqa": false,
        "is_ocb": true,
        "is_kosher": false,
        "value_added_promotion_description": null,
        "description": null,
        "serving_suggestion": null,
        "tasting_note": "Golden yellow colour with a thick head; aromas of fragant hops, citrus and roasted malt with yeasty tones; dryish, medium bodied, fresh, smooth and creamy, with forward hop and grain/cereal flavours; crisp and refreshing on the finish.",
        "updated_at": "2018-10-04T14:18:21.962Z",
        "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/517797/images/thumb.png",
        "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/517797/images/full.jpeg",
        "varietal": "Kolsch",
        "style": null,
        "tertiary_category": "Pale Hybrid Beer",
        "sugar_in_grams_per_liter": null,
        "clearance_sale_savings_in_cents": 0,
        "has_clearance_sale": false,
        "product_no": 517797
    },
    {
        "id": 576926,
        "is_dead": false,
        "name": "Beau's Lug Tread",
        "tags": "beau's beaus lug tread beer hybrid canada ontario all natural brewing can",
        "is_discontinued": false,
        "price_in_cents": 325,
        "regular_price_in_cents": 325,
        "limited_time_offer_savings_in_cents": 0,
        "limited_time_offer_ends_on": null,
        "bonus_reward_miles": 0,
        "bonus_reward_miles_ends_on": null,
        "stock_type": "LCBO",
        "primary_category": "Beer",
        "secondary_category": "Hybrid",
        "origin": "Canada, Ontario",
        "package": "473 mL can",
        "package_unit_type": "can",
        "package_unit_volume_in_milliliters": 473,
        "total_package_units": 1,
        "volume_in_milliliters": 473,
        "alcohol_content": 520,
        "price_per_liter_of_alcohol_in_cents": 1321,
        "price_per_liter_in_cents": 687,
        "inventory_count": 26531,
        "inventory_volume_in_milliliters": 12549163,
        "inventory_price_in_cents": 8622575,
        "sugar_content": null,
        "producer_name": "Beau's All Natural Brewing",
        "released_on": "2012-05-11",
        "has_value_added_promotion": false,
        "has_limited_time_offer": false,
        "has_bonus_reward_miles": false,
        "is_seasonal": false,
        "is_vqa": false,
        "is_ocb": true,
        "is_kosher": false,
        "value_added_promotion_description": null,
        "description": null,
        "serving_suggestion": null,
        "tasting_note": "Golden yellow colour with a thick head; aromas of fragant hops, citrus and roasted malt with yeasty tones; dryish, medium bodied, fresh, smooth and creamy, with forward hop and grain/cereal flavours; crisp and refreshing on the finish.",
        "updated_at": "2018-10-04T14:18:21.709Z",
        "image_thumb_url": null,
        "image_url": null,
        "varietal": "Kolsch",
        "style": "Medium & Malty",
        "tertiary_category": "Pale Hybrid Beer",
        "sugar_in_grams_per_liter": null,
        "clearance_sale_savings_in_cents": 0,
        "has_clearance_sale": false,
        "product_no": 576926
    },
    {
        "id": 575365,
        "is_dead": false,
        "name": "Beau's Full Time IPA",
        "tags": "beau's beaus full time ipa beer ale canada ontario all natural brewing can",
        "is_discontinued": false,
        "price_in_cents": 395,
        "regular_price_in_cents": 395,
        "limited_time_offer_savings_in_cents": 0,
        "limited_time_offer_ends_on": null,
        "bonus_reward_miles": 0,
        "bonus_reward_miles_ends_on": null,
        "stock_type": "LCBO",
        "primary_category": "Beer",
        "secondary_category": "Ale",
        "origin": "Canada, Ontario",
        "package": "473 mL can",
        "package_unit_type": "can",
        "package_unit_volume_in_milliliters": 473,
        "total_package_units": 1,
        "volume_in_milliliters": 473,
        "alcohol_content": 670,
        "price_per_liter_of_alcohol_in_cents": 1246,
        "price_per_liter_in_cents": 835,
        "inventory_count": 18518,
        "inventory_volume_in_milliliters": 8759014,
        "inventory_price_in_cents": 7314610,
        "sugar_content": null,
        "producer_name": "Beau's All Natural Brewing",
        "released_on": "2018-07-03",
        "has_value_added_promotion": false,
        "has_limited_time_offer": false,
        "has_bonus_reward_miles": false,
        "is_seasonal": false,
        "is_vqa": false,
        "is_ocb": true,
        "is_kosher": false,
        "value_added_promotion_description": null,
        "description": null,
        "serving_suggestion": "Serve with Mexican, Thai or Sichuan cuisine.",
        "tasting_note": "The West Coast IPA style is driven by hops, and Full Time delivers with aromas of tropical fruit, citrus and pine. On the palate its medium bodied and creamy in texture, with pronounced fruit flavours, underscored by citrus and sweet malt. Moderate hop bitterness is countered by malt on the lengthy and balanced finish.",
        "updated_at": "2018-10-04T14:18:21.015Z",
        "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/575365/images/thumb.png",
        "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/575365/images/full.jpeg",
        "varietal": "American Pale Ale",
        "style": "Medium & Hoppy",
        "tertiary_category": "India Pale Ale (IPA)",
        "sugar_in_grams_per_liter": null,
        "clearance_sale_savings_in_cents": 0,
        "has_clearance_sale": false,
        "product_no": 575365
    },
    {
        "id": 576868,
        "is_dead": false,
        "name": "Beau's Mix Fall 2018",
        "tags": "beau's beaus mix fall 2018 beer gift and sampler packs canada ontario all natural brewing bottle",
        "is_discontinued": false,
        "price_in_cents": 2195,
        "regular_price_in_cents": 2195,
        "limited_time_offer_savings_in_cents": 0,
        "limited_time_offer_ends_on": null,
        "bonus_reward_miles": 0,
        "bonus_reward_miles_ends_on": null,
        "stock_type": "LCBO",
        "primary_category": "Beer",
        "secondary_category": "Gift and Sampler Packs",
        "origin": "Canada, Ontario",
        "package": "4x600 mL bottle",
        "package_unit_type": "bottle",
        "package_unit_volume_in_milliliters": 600,
        "total_package_units": 4,
        "volume_in_milliliters": 2400,
        "alcohol_content": 500,
        "price_per_liter_of_alcohol_in_cents": 1829,
        "price_per_liter_in_cents": 914,
        "inventory_count": 3347,
        "inventory_volume_in_milliliters": 8032800,
        "inventory_price_in_cents": 7346665,
        "sugar_content": null,
        "producer_name": "Beau's All Natural Brewing",
        "released_on": null,
        "has_value_added_promotion": false,
        "has_limited_time_offer": false,
        "has_bonus_reward_miles": false,
        "is_seasonal": true,
        "is_vqa": false,
        "is_ocb": false,
        "is_kosher": false,
        "value_added_promotion_description": null,
        "description": null,
        "serving_suggestion": null,
        "tasting_note": null,
        "updated_at": "2018-10-04T14:18:22.344Z",
        "image_thumb_url": null,
        "image_url": null,
        "varietal": "Taster Pack",
        "style": null,
        "tertiary_category": "Taster Pack",
        "sugar_in_grams_per_liter": null,
        "clearance_sale_savings_in_cents": 0,
        "has_clearance_sale": false,
        "product_no": 576868
    },
    {
        "id": 436899,
        "is_dead": false,
        "name": "Beau's Farm Table Marzen",
        "tags": "beau's beaus farm table marzen beer lager canada ontario all natural brewing bottle",
        "is_discontinued": false,
        "price_in_cents": 595,
        "regular_price_in_cents": 595,
        "limited_time_offer_savings_in_cents": 0,
        "limited_time_offer_ends_on": null,
        "bonus_reward_miles": 0,
        "bonus_reward_miles_ends_on": null,
        "stock_type": "LCBO",
        "primary_category": "Beer",
        "secondary_category": "Lager",
        "origin": "Canada, Ontario",
        "package": "600 mL bottle",
        "package_unit_type": "bottle",
        "package_unit_volume_in_milliliters": 600,
        "total_package_units": 1,
        "volume_in_milliliters": 600,
        "alcohol_content": 550,
        "price_per_liter_of_alcohol_in_cents": 1803,
        "price_per_liter_in_cents": 991,
        "inventory_count": 3441,
        "inventory_volume_in_milliliters": 2064600,
        "inventory_price_in_cents": 2047395,
        "sugar_content": null,
        "producer_name": "Beau's All Natural Brewing",
        "released_on": "2018-06-27",
        "has_value_added_promotion": false,
        "has_limited_time_offer": false,
        "has_bonus_reward_miles": false,
        "is_seasonal": true,
        "is_vqa": false,
        "is_ocb": true,
        "is_kosher": false,
        "value_added_promotion_description": null,
        "description": null,
        "serving_suggestion": "A great pairing with pork schnitzel, soft pretzels and mustard, beef rouladen.",
        "tasting_note": "Beau's Farm Table Series beers are inspired by classic styles. Märzen is the traditional Oktoberfest style ? malty, biscuity flavours are balanced by an assertive blend of hops, which contribute bitterness and a clean finish. Serve with soft pretzels and plenty of mustard.",
        "updated_at": "2018-10-04T14:18:20.637Z",
        "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/436899/images/thumb.png",
        "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/436899/images/full.jpeg",
        "varietal": "Oktoberfest/Marzen",
        "style": null,
        "tertiary_category": "Amber Lager",
        "sugar_in_grams_per_liter": null,
        "clearance_sale_savings_in_cents": 0,
        "has_clearance_sale": false,
        "product_no": 436899
    },
    {
        "id": 572065,
        "is_dead": false,
        "name": "Beau's B-Side Tagwerk",
        "tags": "beau's beaus b side b-side bside tagwerk beer ale canada ontario all natural brewing bottle",
        "is_discontinued": false,
        "price_in_cents": 595,
        "regular_price_in_cents": 595,
        "limited_time_offer_savings_in_cents": 0,
        "limited_time_offer_ends_on": null,
        "bonus_reward_miles": 0,
        "bonus_reward_miles_ends_on": null,
        "stock_type": "LCBO",
        "primary_category": "Beer",
        "secondary_category": "Ale",
        "origin": "Canada, Ontario",
        "package": "600 mL bottle",
        "package_unit_type": "bottle",
        "package_unit_volume_in_milliliters": 600,
        "total_package_units": 1,
        "volume_in_milliliters": 600,
        "alcohol_content": 690,
        "price_per_liter_of_alcohol_in_cents": 1437,
        "price_per_liter_in_cents": 991,
        "inventory_count": 2970,
        "inventory_volume_in_milliliters": 1782000,
        "inventory_price_in_cents": 1767150,
        "sugar_content": null,
        "producer_name": "Beau's All Natural Brewing",
        "released_on": null,
        "has_value_added_promotion": false,
        "has_limited_time_offer": false,
        "has_bonus_reward_miles": false,
        "is_seasonal": true,
        "is_vqa": false,
        "is_ocb": true,
        "is_kosher": false,
        "value_added_promotion_description": null,
        "description": null,
        "serving_suggestion": null,
        "tasting_note": null,
        "updated_at": "2018-10-04T14:18:19.897Z",
        "image_thumb_url": null,
        "image_url": null,
        "varietal": null,
        "style": null,
        "tertiary_category": null,
        "sugar_in_grams_per_liter": null,
        "clearance_sale_savings_in_cents": 0,
        "has_clearance_sale": false,
        "product_no": 572065
    },
    {
        "id": 539056,
        "is_dead": false,
        "name": "Beau's Tom Green Cherry Milk Stout",
        "tags": "beau's beaus tom green cherry milk stout beer ale canada ontario all natural brewing bottle",
        "is_discontinued": false,
        "price_in_cents": 595,
        "regular_price_in_cents": 595,
        "limited_time_offer_savings_in_cents": 0,
        "limited_time_offer_ends_on": null,
        "bonus_reward_miles": 0,
        "bonus_reward_miles_ends_on": null,
        "stock_type": "LCBO",
        "primary_category": "Beer",
        "secondary_category": "Ale",
        "origin": "Canada, Ontario",
        "package": "600 mL bottle",
        "package_unit_type": "bottle",
        "package_unit_volume_in_milliliters": 600,
        "total_package_units": 1,
        "volume_in_milliliters": 600,
        "alcohol_content": 560,
        "price_per_liter_of_alcohol_in_cents": 1770,
        "price_per_liter_in_cents": 991,
        "inventory_count": 2720,
        "inventory_volume_in_milliliters": 1632000,
        "inventory_price_in_cents": 1618400,
        "sugar_content": null,
        "producer_name": "Beau's All Natural Brewing",
        "released_on": "2018-09-21",
        "has_value_added_promotion": false,
        "has_limited_time_offer": false,
        "has_bonus_reward_miles": false,
        "is_seasonal": true,
        "is_vqa": false,
        "is_ocb": true,
        "is_kosher": false,
        "value_added_promotion_description": null,
        "description": null,
        "serving_suggestion": "Serve chilled with not-too-sweet cherry based desserts or BBQ pork and roast poultry with cherry coulis.",
        "tasting_note": "The latest version of the Tom Green Milk Stout; this one is brewed with added organic cherries. It pours a dark amber brown colour with thick head. Exhibits aromas and flavours of dark cherry jam, malt, coffee and chocolate with toasted pie filling. Palate is medium sweet, smooth and silky with a roast cherry fruit finish.",
        "updated_at": "2018-10-04T14:18:23.171Z",
        "image_thumb_url": null,
        "image_url": null,
        "varietal": "Stout",
        "style": "Medium & Roasted",
        "tertiary_category": "Stout",
        "sugar_in_grams_per_liter": null,
        "clearance_sale_savings_in_cents": 0,
        "has_clearance_sale": false,
        "product_no": 539056
    },
    {
        "id": 538892,
        "is_dead": false,
        "name": "Beau's Three Knocks",
        "tags": "beau's beaus three knocks beer ale canada ontario all natural brewing bottle",
        "is_discontinued": false,
        "price_in_cents": 795,
        "regular_price_in_cents": 795,
        "limited_time_offer_savings_in_cents": 0,
        "limited_time_offer_ends_on": null,
        "bonus_reward_miles": 0,
        "bonus_reward_miles_ends_on": null,
        "stock_type": "LCBO",
        "primary_category": "Beer",
        "secondary_category": "Ale",
        "origin": "Canada, Ontario",
        "package": "600 mL bottle",
        "package_unit_type": "bottle",
        "package_unit_volume_in_milliliters": 600,
        "total_package_units": 1,
        "volume_in_milliliters": 600,
        "alcohol_content": 700,
        "price_per_liter_of_alcohol_in_cents": 1892,
        "price_per_liter_in_cents": 1325,
        "inventory_count": 2691,
        "inventory_volume_in_milliliters": 1614600,
        "inventory_price_in_cents": 2139345,
        "sugar_content": null,
        "producer_name": "Beau's All Natural Brewing",
        "released_on": null,
        "has_value_added_promotion": false,
        "has_limited_time_offer": false,
        "has_bonus_reward_miles": false,
        "is_seasonal": true,
        "is_vqa": false,
        "is_ocb": true,
        "is_kosher": false,
        "value_added_promotion_description": null,
        "description": null,
        "serving_suggestion": null,
        "tasting_note": null,
        "updated_at": "2018-10-04T14:18:23.024Z",
        "image_thumb_url": null,
        "image_url": null,
        "varietal": null,
        "style": null,
        "tertiary_category": null,
        "sugar_in_grams_per_liter": null,
        "clearance_sale_savings_in_cents": 0,
        "has_clearance_sale": false,
        "product_no": 538892
    },
    {
        "id": 625327,
        "is_dead": false,
        "name": "Beau's Four Flower Gruit",
        "tags": "beau's beaus four flower gruit beer ale canada ontario all natural brewing bottle",
        "is_discontinued": false,
        "price_in_cents": 595,
        "regular_price_in_cents": 595,
        "limited_time_offer_savings_in_cents": 0,
        "limited_time_offer_ends_on": null,
        "bonus_reward_miles": 0,
        "bonus_reward_miles_ends_on": null,
        "stock_type": "LCBO",
        "primary_category": "Beer",
        "secondary_category": "Ale",
        "origin": "Canada, Ontario",
        "package": "600 mL bottle",
        "package_unit_type": "bottle",
        "package_unit_volume_in_milliliters": 600,
        "total_package_units": 1,
        "volume_in_milliliters": 600,
        "alcohol_content": 560,
        "price_per_liter_of_alcohol_in_cents": 1770,
        "price_per_liter_in_cents": 991,
        "inventory_count": 2326,
        "inventory_volume_in_milliliters": 1395600,
        "inventory_price_in_cents": 1383970,
        "sugar_content": null,
        "producer_name": "Beau's All Natural Brewing",
        "released_on": "2018-09-21",
        "has_value_added_promotion": false,
        "has_limited_time_offer": false,
        "has_bonus_reward_miles": false,
        "is_seasonal": true,
        "is_vqa": false,
        "is_ocb": false,
        "is_kosher": false,
        "value_added_promotion_description": null,
        "description": null,
        "serving_suggestion": "Serve chilled in a wine glass. Savour on its own or pair with light goat or blue cheeses. Also use to enhance food recipes, including stocks and sauces.",
        "tasting_note": "An inspired version of gruit ale. This batch includes four organic flowers: red clover, elderflower, borage and honeysuckle. It's hazy orange in colour with perfumed floral and fruit aromas. Light and rounded palate, with malty notes and flavours of citrus, herb, red berry and apple. Clean and crisp finish. Serve chilled.",
        "updated_at": "2018-10-04T14:18:20.889Z",
        "image_thumb_url": null,
        "image_url": null,
        "varietal": "Flavoured Beer",
        "style": "Medium & Fruity",
        "tertiary_category": "Flavoured Beer",
        "sugar_in_grams_per_liter": null,
        "clearance_sale_savings_in_cents": 0,
        "has_clearance_sale": false,
        "product_no": 625327
    },
    {
        "id": 560003,
        "is_dead": false,
        "name": "Beau's Summer Mixed Pack",
        "tags": "beau's beaus summer mixed pack beer gift and sampler packs canada ontario all natural brewing bottle",
        "is_discontinued": false,
        "price_in_cents": 2195,
        "regular_price_in_cents": 2195,
        "limited_time_offer_savings_in_cents": 0,
        "limited_time_offer_ends_on": null,
        "bonus_reward_miles": 0,
        "bonus_reward_miles_ends_on": null,
        "stock_type": "LCBO",
        "primary_category": "Beer",
        "secondary_category": "Gift and Sampler Packs",
        "origin": "Canada, Ontario",
        "package": "4x600 mL bottle",
        "package_unit_type": "bottle",
        "package_unit_volume_in_milliliters": 600,
        "total_package_units": 4,
        "volume_in_milliliters": 2400,
        "alcohol_content": 520,
        "price_per_liter_of_alcohol_in_cents": 1758,
        "price_per_liter_in_cents": 914,
        "inventory_count": 442,
        "inventory_volume_in_milliliters": 1060800,
        "inventory_price_in_cents": 970190,
        "sugar_content": null,
        "producer_name": "Beau's All Natural Brewing",
        "released_on": "2018-05-22",
        "has_value_added_promotion": false,
        "has_limited_time_offer": false,
        "has_bonus_reward_miles": false,
        "is_seasonal": true,
        "is_vqa": false,
        "is_ocb": true,
        "is_kosher": false,
        "value_added_promotion_description": null,
        "description": null,
        "serving_suggestion": "Serve up poolside.",
        "tasting_note": "Beau's has a knack for assembling mix packs that embody the season perfectly and this year's summer mix is no exception. Cali Common Saison, Buenos Dias Gruit, Blood Simple Blood Orange Witbier and the classic Lug Tread are perfect companions to warm summer nights.",
        "updated_at": "2018-10-04T14:18:22.763Z",
        "image_thumb_url": null,
        "image_url": null,
        "varietal": "Taster Pack",
        "style": null,
        "tertiary_category": "Taster Pack",
        "sugar_in_grams_per_liter": null,
        "clearance_sale_savings_in_cents": 0,
        "has_clearance_sale": false,
        "product_no": 560003
    },
    {
        "id": 365593,
        "is_dead": false,
        "name": "Beau's B-Side Kissmeyer Nordic Pale Ale",
        "tags": "beau's beaus b side b-side bside kissmeyer nordic pale ale beer canada ontario all natural brewing bottle",
        "is_discontinued": false,
        "price_in_cents": 645,
        "regular_price_in_cents": 645,
        "limited_time_offer_savings_in_cents": 0,
        "limited_time_offer_ends_on": null,
        "bonus_reward_miles": 0,
        "bonus_reward_miles_ends_on": null,
        "stock_type": "LCBO",
        "primary_category": "Beer",
        "secondary_category": "Ale",
        "origin": "Canada, Ontario",
        "package": "600 mL bottle",
        "package_unit_type": "bottle",
        "package_unit_volume_in_milliliters": 600,
        "total_package_units": 1,
        "volume_in_milliliters": 600,
        "alcohol_content": 600,
        "price_per_liter_of_alcohol_in_cents": 1791,
        "price_per_liter_in_cents": 1075,
        "inventory_count": 1503,
        "inventory_volume_in_milliliters": 901800,
        "inventory_price_in_cents": 969435,
        "sugar_content": null,
        "producer_name": "Beau's All Natural Brewing",
        "released_on": "2014-11-05",
        "has_value_added_promotion": false,
        "has_limited_time_offer": false,
        "has_bonus_reward_miles": false,
        "is_seasonal": false,
        "is_vqa": false,
        "is_ocb": true,
        "is_kosher": false,
        "value_added_promotion_description": null,
        "description": null,
        "serving_suggestion": "Serve with herb-crusted pork chops, grilled sausages, fried calamari or pretzels.",
        "tasting_note": "Clear, bright medium amber; on the nose there are pronounced notes of Christmas tree, pineapple, pink grapefruit and spice; on the palate it is dry and full bodied, with flavours of grapefruit, heather, cranberry, pine and bitter dried herb.",
        "updated_at": "2018-10-04T14:18:19.771Z",
        "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/365593/images/thumb.png",
        "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/365593/images/full.jpeg",
        "varietal": "American Pale Ale",
        "style": "Medium & Floral",
        "tertiary_category": "Pale Ale",
        "sugar_in_grams_per_liter": null,
        "clearance_sale_savings_in_cents": 0,
        "has_clearance_sale": false,
        "product_no": 365593
    },
    {
        "id": 576850,
        "is_dead": false,
        "name": "Beau's Farm Table Hopfenlager",
        "tags": "beau's beaus farm table hopfenlager beer lager canada ontario all natural brewing bottle",
        "is_discontinued": false,
        "price_in_cents": 595,
        "regular_price_in_cents": 595,
        "limited_time_offer_savings_in_cents": 0,
        "limited_time_offer_ends_on": null,
        "bonus_reward_miles": 0,
        "bonus_reward_miles_ends_on": null,
        "stock_type": "LCBO",
        "primary_category": "Beer",
        "secondary_category": "Lager",
        "origin": "Canada, Ontario",
        "package": "600 mL bottle",
        "package_unit_type": "bottle",
        "package_unit_volume_in_milliliters": 600,
        "total_package_units": 1,
        "volume_in_milliliters": 600,
        "alcohol_content": 660,
        "price_per_liter_of_alcohol_in_cents": 1502,
        "price_per_liter_in_cents": 991,
        "inventory_count": 1209,
        "inventory_volume_in_milliliters": 725400,
        "inventory_price_in_cents": 719355,
        "sugar_content": null,
        "producer_name": "Beau's All Natural Brewing",
        "released_on": null,
        "has_value_added_promotion": false,
        "has_limited_time_offer": false,
        "has_bonus_reward_miles": false,
        "is_seasonal": true,
        "is_vqa": false,
        "is_ocb": true,
        "is_kosher": false,
        "value_added_promotion_description": null,
        "description": null,
        "serving_suggestion": null,
        "tasting_note": null,
        "updated_at": "2018-10-04T14:18:20.519Z",
        "image_thumb_url": null,
        "image_url": null,
        "varietal": "Pale Lager",
        "style": "Medium & Hoppy",
        "tertiary_category": "Pale Lager",
        "sugar_in_grams_per_liter": null,
        "clearance_sale_savings_in_cents": 0,
        "has_clearance_sale": false,
        "product_no": 576850
    },
    {
        "id": 519959,
        "is_dead": false,
        "name": "Beau's Tom Green Summer Stout",
        "tags": "beau's beaus tom green summer stout beer ale canada ontario all natural brewing bottle",
        "is_discontinued": false,
        "price_in_cents": 595,
        "regular_price_in_cents": 595,
        "limited_time_offer_savings_in_cents": 0,
        "limited_time_offer_ends_on": null,
        "bonus_reward_miles": 0,
        "bonus_reward_miles_ends_on": null,
        "stock_type": "LCBO",
        "primary_category": "Beer",
        "secondary_category": "Ale",
        "origin": "Canada, Ontario",
        "package": "600 mL bottle",
        "package_unit_type": "bottle",
        "package_unit_volume_in_milliliters": 600,
        "total_package_units": 1,
        "volume_in_milliliters": 600,
        "alcohol_content": 500,
        "price_per_liter_of_alcohol_in_cents": 1983,
        "price_per_liter_in_cents": 991,
        "inventory_count": 440,
        "inventory_volume_in_milliliters": 264000,
        "inventory_price_in_cents": 261800,
        "sugar_content": null,
        "producer_name": "Beau's All Natural Brewing",
        "released_on": "2018-07-03",
        "has_value_added_promotion": false,
        "has_limited_time_offer": false,
        "has_bonus_reward_miles": false,
        "is_seasonal": true,
        "is_vqa": false,
        "is_ocb": true,
        "is_kosher": false,
        "value_added_promotion_description": null,
        "description": null,
        "serving_suggestion": "Serve with shellfish, game meats, baked beans, meat pies.",
        "tasting_note": "A blond stout is made by infusing golden ale with the rich aroma and flavours of coffee and cocoa. Enjoy aromas and flavours of freshly brewed light-roast coffee, dark chocolate and spice, with just a hint of sweetness on the finish. Serve with venison, smoky barbecue, creamy clam chowder or blue cheese.",
        "updated_at": "2018-10-04T14:18:23.300Z",
        "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/519959/images/thumb.png",
        "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/519959/images/full.jpeg",
        "varietal": "Stout",
        "style": "Medium & Roasted",
        "tertiary_category": "Stout",
        "sugar_in_grams_per_liter": null,
        "clearance_sale_savings_in_cents": 0,
        "has_clearance_sale": false,
        "product_no": 519959
    },
    {
        "id": 525642,
        "is_dead": false,
        "name": "Beau's Fall Mixed Pack",
        "tags": "beau's beaus fall mixed pack beer gift and sampler packs canada ontario all natural brewing bottle",
        "is_discontinued": false,
        "price_in_cents": 2195,
        "regular_price_in_cents": 2195,
        "limited_time_offer_savings_in_cents": 0,
        "limited_time_offer_ends_on": null,
        "bonus_reward_miles": 0,
        "bonus_reward_miles_ends_on": null,
        "stock_type": "LCBO",
        "primary_category": "Beer",
        "secondary_category": "Gift and Sampler Packs",
        "origin": "Canada, Ontario",
        "package": "4x600 mL bottle",
        "package_unit_type": "bottle",
        "package_unit_volume_in_milliliters": 600,
        "total_package_units": 4,
        "volume_in_milliliters": 2400,
        "alcohol_content": 600,
        "price_per_liter_of_alcohol_in_cents": 1524,
        "price_per_liter_in_cents": 914,
        "inventory_count": 88,
        "inventory_volume_in_milliliters": 211200,
        "inventory_price_in_cents": 193160,
        "sugar_content": null,
        "producer_name": "Beau's All Natural Brewing",
        "released_on": "2017-09-18",
        "has_value_added_promotion": false,
        "has_limited_time_offer": false,
        "has_bonus_reward_miles": false,
        "is_seasonal": true,
        "is_vqa": false,
        "is_ocb": true,
        "is_kosher": false,
        "value_added_promotion_description": null,
        "description": null,
        "serving_suggestion": "Perfect for pot-luck gatherings, a style for every palate.",
        "tasting_note": "The eagerly anticipated Fall Mix pack from Beau's includes Lugtread Lagered Ale, Sargeant Stripes Export Stout, Cranberry Derby Cranberry Oat Ale and Spice Principle Spiced Weissebier. Explore the world of craft beer styles!",
        "updated_at": "2018-10-04T14:18:20.402Z",
        "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/525642/images/thumb.png",
        "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/525642/images/full.jpeg",
        "varietal": "Taster Pack",
        "style": null,
        "tertiary_category": "Taster Pack",
        "sugar_in_grams_per_liter": null,
        "clearance_sale_savings_in_cents": 0,
        "has_clearance_sale": false,
        "product_no": 525642
    },
    {
        "id": 514943,
        "is_dead": false,
        "name": "Beau's Halcyon Barrel House Infinity Mirror Brett IPA",
        "tags": "beau's beaus halcyon barrel house infinity mirror brett ipa beer ale canada ontario all natural brewing bottle",
        "is_discontinued": false,
        "price_in_cents": 994,
        "regular_price_in_cents": 994,
        "limited_time_offer_savings_in_cents": 0,
        "limited_time_offer_ends_on": null,
        "bonus_reward_miles": 0,
        "bonus_reward_miles_ends_on": null,
        "stock_type": "LCBO",
        "primary_category": "Beer",
        "secondary_category": "Ale",
        "origin": "Canada, Ontario",
        "package": "750 mL bottle",
        "package_unit_type": "bottle",
        "package_unit_volume_in_milliliters": 750,
        "total_package_units": 1,
        "volume_in_milliliters": 750,
        "alcohol_content": 650,
        "price_per_liter_of_alcohol_in_cents": 2038,
        "price_per_liter_in_cents": 1325,
        "inventory_count": 264,
        "inventory_volume_in_milliliters": 198000,
        "inventory_price_in_cents": 262416,
        "sugar_content": null,
        "producer_name": "Beau's All Natural Brewing",
        "released_on": "2018-07-05",
        "has_value_added_promotion": false,
        "has_limited_time_offer": false,
        "has_bonus_reward_miles": false,
        "is_seasonal": true,
        "is_vqa": false,
        "is_ocb": true,
        "is_kosher": false,
        "value_added_promotion_description": null,
        "description": null,
        "serving_suggestion": "Serve with barbecued pork, mature cheeses or fish with a citrus-based sauce.",
        "tasting_note": "Infinity Mirror is a wild-fermented India pale ale that is aged in red wine barrels. Aromas of grapefruit, baking spice, banana apricot and pineapple. On the palate, it is rich, creamy and frothy with flavours of tangy grapefruit, with banana and toasted nut. Pair with mature cheeses, kimchee or barbecued pork.",
        "updated_at": "2018-10-04T14:18:21.394Z",
        "image_thumb_url": null,
        "image_url": null,
        "varietal": "India Pale Ale (Ipa)",
        "style": "Medium & Hoppy",
        "tertiary_category": "India Pale Ale (IPA)",
        "sugar_in_grams_per_liter": null,
        "clearance_sale_savings_in_cents": 0,
        "has_clearance_sale": false,
        "product_no": 514943
    },
    {
        "id": 546861,
        "is_dead": false,
        "name": "Beau's Halcyon Barrel House Gravity Well",
        "tags": "beau's beaus halcyon barrel house gravity well beer ale canada ontario all natural brewing bottle",
        "is_discontinued": false,
        "price_in_cents": 1695,
        "regular_price_in_cents": 1695,
        "limited_time_offer_savings_in_cents": 0,
        "limited_time_offer_ends_on": null,
        "bonus_reward_miles": 0,
        "bonus_reward_miles_ends_on": null,
        "stock_type": "LCBO",
        "primary_category": "Beer",
        "secondary_category": "Ale",
        "origin": "Canada, Ontario",
        "package": "750 mL bottle",
        "package_unit_type": "bottle",
        "package_unit_volume_in_milliliters": 750,
        "total_package_units": 1,
        "volume_in_milliliters": 750,
        "alcohol_content": 900,
        "price_per_liter_of_alcohol_in_cents": 2511,
        "price_per_liter_in_cents": 2260,
        "inventory_count": 156,
        "inventory_volume_in_milliliters": 117000,
        "inventory_price_in_cents": 264420,
        "sugar_content": null,
        "producer_name": "Beau's All Natural Brewing",
        "released_on": null,
        "has_value_added_promotion": false,
        "has_limited_time_offer": false,
        "has_bonus_reward_miles": false,
        "is_seasonal": true,
        "is_vqa": false,
        "is_ocb": true,
        "is_kosher": false,
        "value_added_promotion_description": null,
        "description": null,
        "serving_suggestion": null,
        "tasting_note": null,
        "updated_at": "2018-10-04T14:18:21.272Z",
        "image_thumb_url": null,
        "image_url": null,
        "varietal": "Sour",
        "style": "Medium & Tart",
        "tertiary_category": "Sour",
        "sugar_in_grams_per_liter": null,
        "clearance_sale_savings_in_cents": 0,
        "has_clearance_sale": false,
        "product_no": 546861
    },
    {
        "id": 589325,
        "is_dead": false,
        "name": "Beau's de Berry's Treasure",
        "tags": "beau's beaus de berry's berrys treasure beer ale canada ontario all natural brewing bottle",
        "is_discontinued": false,
        "price_in_cents": 795,
        "regular_price_in_cents": 795,
        "limited_time_offer_savings_in_cents": 0,
        "limited_time_offer_ends_on": null,
        "bonus_reward_miles": 0,
        "bonus_reward_miles_ends_on": null,
        "stock_type": "LCBO",
        "primary_category": "Beer",
        "secondary_category": "Ale",
        "origin": "Canada, Ontario",
        "package": "600 mL bottle",
        "package_unit_type": "bottle",
        "package_unit_volume_in_milliliters": 600,
        "total_package_units": 1,
        "volume_in_milliliters": 600,
        "alcohol_content": 450,
        "price_per_liter_of_alcohol_in_cents": 2944,
        "price_per_liter_in_cents": 1325,
        "inventory_count": 194,
        "inventory_volume_in_milliliters": 116400,
        "inventory_price_in_cents": 154230,
        "sugar_content": null,
        "producer_name": "Beau's All Natural Brewing",
        "released_on": "2018-07-25",
        "has_value_added_promotion": false,
        "has_limited_time_offer": false,
        "has_bonus_reward_miles": false,
        "is_seasonal": true,
        "is_vqa": false,
        "is_ocb": true,
        "is_kosher": false,
        "value_added_promotion_description": null,
        "description": null,
        "serving_suggestion": null,
        "tasting_note": "Gose is a German-style beer with a characteristic saltiness. This locally produced version of Gose is brewed with added organic black raspberries and rhubarb that enhance the aromas and add a refreshing balanced tanginess to the finish. The palate is medium in body, smooth with light sweetness and toasted grainy notes.",
        "updated_at": "2018-10-04T14:18:20.273Z",
        "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/589325/images/thumb.png",
        "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/589325/images/full.jpeg",
        "varietal": "Sour",
        "style": "Medium & Fruity",
        "tertiary_category": "Sour",
        "sugar_in_grams_per_liter": null,
        "clearance_sale_savings_in_cents": 0,
        "has_clearance_sale": false,
        "product_no": 589325
    },
    {
        "id": 519942,
        "is_dead": false,
        "name": "Beau's Farm Table Saison",
        "tags": "beau's beaus farm table saison beer ale canada ontario all natural brewing bottle",
        "is_discontinued": true,
        "price_in_cents": 595,
        "regular_price_in_cents": 595,
        "limited_time_offer_savings_in_cents": 0,
        "limited_time_offer_ends_on": null,
        "bonus_reward_miles": 0,
        "bonus_reward_miles_ends_on": null,
        "stock_type": "LCBO",
        "primary_category": "Beer",
        "secondary_category": "Ale",
        "origin": "Canada, Ontario",
        "package": "600 mL bottle",
        "package_unit_type": "bottle",
        "package_unit_volume_in_milliliters": 600,
        "total_package_units": 1,
        "volume_in_milliliters": 600,
        "alcohol_content": 470,
        "price_per_liter_of_alcohol_in_cents": 2109,
        "price_per_liter_in_cents": 991,
        "inventory_count": 131,
        "inventory_volume_in_milliliters": 78600,
        "inventory_price_in_cents": 77945,
        "sugar_content": null,
        "producer_name": "Beau's All Natural Brewing",
        "released_on": "2018-07-03",
        "has_value_added_promotion": false,
        "has_limited_time_offer": false,
        "has_bonus_reward_miles": false,
        "is_seasonal": true,
        "is_vqa": false,
        "is_ocb": true,
        "is_kosher": false,
        "value_added_promotion_description": null,
        "description": null,
        "serving_suggestion": "Serve with sausages, mature cheeses or grilled salmon.",
        "tasting_note": "Beau's Farm Table Series is inspired by tradition, and each beer is brewed to a classic style. Saison is a cloudy gold, with aromas of tropical fruit, citrus, spice and piney hops. On the palate, it is balanced, and superbly food-friendly with fruity and savoury notes. Serve with sausages, mature cheeses or grilled salmon.",
        "updated_at": "2018-10-04T14:18:20.759Z",
        "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/519942/images/thumb.png",
        "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/519942/images/full.jpeg",
        "varietal": "Belgian Ale",
        "style": "Medium & Fruity",
        "tertiary_category": "Belgian Ale",
        "sugar_in_grams_per_liter": null,
        "clearance_sale_savings_in_cents": 0,
        "has_clearance_sale": false,
        "product_no": 519942
    },
    {
        "id": 539031,
        "is_dead": false,
        "name": "Beau's Cavalier Bleu",
        "tags": "beau's beaus cavalier bleu beer ale canada ontario all natural brewing bottle",
        "is_discontinued": false,
        "price_in_cents": 795,
        "regular_price_in_cents": 795,
        "limited_time_offer_savings_in_cents": 0,
        "limited_time_offer_ends_on": null,
        "bonus_reward_miles": 0,
        "bonus_reward_miles_ends_on": null,
        "stock_type": "LCBO",
        "primary_category": "Beer",
        "secondary_category": "Ale",
        "origin": "Canada, Ontario",
        "package": "600 mL bottle",
        "package_unit_type": "bottle",
        "package_unit_volume_in_milliliters": 600,
        "total_package_units": 1,
        "volume_in_milliliters": 600,
        "alcohol_content": 600,
        "price_per_liter_of_alcohol_in_cents": 2208,
        "price_per_liter_in_cents": 1325,
        "inventory_count": 91,
        "inventory_volume_in_milliliters": 54600,
        "inventory_price_in_cents": 72345,
        "sugar_content": null,
        "producer_name": "Beau's All Natural Brewing",
        "released_on": "2018-06-29",
        "has_value_added_promotion": false,
        "has_limited_time_offer": false,
        "has_bonus_reward_miles": false,
        "is_seasonal": true,
        "is_vqa": false,
        "is_ocb": true,
        "is_kosher": false,
        "value_added_promotion_description": null,
        "description": null,
        "serving_suggestion": "Serve with venison, duck or lamb.",
        "tasting_note": "Located in Vankleek Hill, south of Hawkesbury, Beau's has been brewing organic beer since 2006. This pale Ale is generously hopped with American and German hop varieties, and infused with organic blueberry juice. Assertive hops, citrus and tangy blueberry flavours lead to a cleansing, pleasingly bitter finish.",
        "updated_at": "2018-10-04T14:18:20.142Z",
        "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/539031/images/thumb.png",
        "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/539031/images/full.jpeg",
        "varietal": "India Pale Ale (Ipa)",
        "style": "Medium & Fruity",
        "tertiary_category": "India Pale Ale (IPA)",
        "sugar_in_grams_per_liter": null,
        "clearance_sale_savings_in_cents": 0,
        "has_clearance_sale": false,
        "product_no": 539031
    }
];

// Available stores from 'Beau's Tom Green Summer Stout'
// lcboapi.com/stores?product_id=519959

class App extends Component {
  constructor(props) {
    super(props);
    this.handleSelectProduct = this.handleSelectProduct.bind(this);
    this.state = {
      selectedProduct: {},
      availableStores: [],
      availableStoresHardCoded: [
          {
              "id": 217,
              "is_dead": false,
              "name": "Queens Quay & Yonge",
              "tags": "queens quay yonge 2 cooper street queen's toronto central toronto-central torontocentral m5e0b8",
              "address_line_1": "2 Cooper Street",
              "address_line_2": "Queen's Quay",
              "city": "Toronto",
              "postal_code": "M5E0B8",
              "telephone": "(416) 864-6777",
              "fax": "(416) 864-6863",
              "latitude": 43.643,
              "longitude": -79.3723,
              "products_count": 5158,
              "inventory_count": 171516,
              "inventory_price_in_cents": 430351519,
              "inventory_volume_in_milliliters": 130207922,
              "has_wheelchair_accessability": true,
              "has_bilingual_services": true,
              "has_product_consultant": true,
              "has_tasting_bar": true,
              "has_beer_cold_room": false,
              "has_special_occasion_permits": false,
              "has_vintages_corner": true,
              "has_parking": true,
              "has_transit_access": true,
              "sunday_open": 660,
              "sunday_close": 1080,
              "monday_open": 540,
              "monday_close": 1320,
              "tuesday_open": 540,
              "tuesday_close": 1320,
              "wednesday_open": 540,
              "wednesday_close": 1320,
              "thursday_open": 540,
              "thursday_close": 1320,
              "friday_open": 540,
              "friday_close": 1320,
              "saturday_open": 540,
              "saturday_close": 1320,
              "updated_at": "2018-10-09T14:15:17.699Z",
              "quantity": 0,
              "updated_on": "2018-09-20",
              "store_no": 217
          },
          {
              "id": 10,
              "is_dead": false,
              "name": "Yonge & Summerhill",
              "tags": "yonge summerhill 10 scrivener square subway toronto central toronto-central torontocentral m4w3y9",
              "address_line_1": "10 Scrivener Square",
              "address_line_2": "Summerhill Subway",
              "city": "Toronto",
              "postal_code": "M4W3Y9",
              "telephone": "(416) 922-0403",
              "fax": "(416) 922-3104",
              "latitude": 43.6809,
              "longitude": -79.3905,
              "products_count": 4977,
              "inventory_count": 160026,
              "inventory_price_in_cents": 439327114,
              "inventory_volume_in_milliliters": 116966922,
              "has_wheelchair_accessability": true,
              "has_bilingual_services": true,
              "has_product_consultant": true,
              "has_tasting_bar": false,
              "has_beer_cold_room": false,
              "has_special_occasion_permits": false,
              "has_vintages_corner": true,
              "has_parking": true,
              "has_transit_access": true,
              "sunday_open": 660,
              "sunday_close": 1080,
              "monday_open": 540,
              "monday_close": 1320,
              "tuesday_open": 540,
              "tuesday_close": 1320,
              "wednesday_open": 540,
              "wednesday_close": 1320,
              "thursday_open": 540,
              "thursday_close": 1320,
              "friday_open": 540,
              "friday_close": 1320,
              "saturday_open": 540,
              "saturday_close": 1320,
              "updated_at": "2018-10-09T14:15:16.848Z",
              "quantity": 0,
              "updated_on": "2018-08-31",
              "store_no": 10
          },
          {
              "id": 1,
              "is_dead": false,
              "name": "Hwy 401 & Weston",
              "tags": "hwy 401 weston 2625d road toronto north toronto-north torontonorth york m9n3w2",
              "address_line_1": "2625D Weston Road",
              "address_line_2": null,
              "city": "North York",
              "postal_code": "M9N3W2",
              "telephone": "(416) 243-3320",
              "fax": "(416) 243-0148",
              "latitude": 43.7127,
              "longitude": -79.531,
              "products_count": 4641,
              "inventory_count": 106753,
              "inventory_price_in_cents": 219285717,
              "inventory_volume_in_milliliters": 90360680,
              "has_wheelchair_accessability": true,
              "has_bilingual_services": true,
              "has_product_consultant": true,
              "has_tasting_bar": false,
              "has_beer_cold_room": false,
              "has_special_occasion_permits": false,
              "has_vintages_corner": true,
              "has_parking": true,
              "has_transit_access": true,
              "sunday_open": 570,
              "sunday_close": 1080,
              "monday_open": 540,
              "monday_close": 1380,
              "tuesday_open": 540,
              "tuesday_close": 1380,
              "wednesday_open": 540,
              "wednesday_close": 1380,
              "thursday_open": 540,
              "thursday_close": 1380,
              "friday_open": 540,
              "friday_close": 1380,
              "saturday_open": 540,
              "saturday_close": 1380,
              "updated_at": "2018-10-09T14:15:19.182Z",
              "quantity": 0,
              "updated_on": "2018-07-10",
              "store_no": 1
          },
          {
              "id": 38,
              "is_dead": false,
              "name": "Rideau & King Edward",
              "tags": "rideau king edward 275 street corner of and st ottawa k1n5y3",
              "address_line_1": "275 Rideau Street",
              "address_line_2": "Corner of King Edward and Rideau St",
              "city": "Ottawa",
              "postal_code": "K1N5Y3",
              "telephone": "(613) 789-5226",
              "fax": "(613) 241-7453",
              "latitude": 45.4288,
              "longitude": -75.6863,
              "products_count": 4783,
              "inventory_count": 114094,
              "inventory_price_in_cents": 269626251,
              "inventory_volume_in_milliliters": 83350702,
              "has_wheelchair_accessability": true,
              "has_bilingual_services": true,
              "has_product_consultant": true,
              "has_tasting_bar": true,
              "has_beer_cold_room": false,
              "has_special_occasion_permits": false,
              "has_vintages_corner": true,
              "has_parking": true,
              "has_transit_access": true,
              "sunday_open": 660,
              "sunday_close": 1080,
              "monday_open": 570,
              "monday_close": 1320,
              "tuesday_open": 570,
              "tuesday_close": 1320,
              "wednesday_open": 570,
              "wednesday_close": 1320,
              "thursday_open": 570,
              "thursday_close": 1320,
              "friday_open": 570,
              "friday_close": 1320,
              "saturday_open": 570,
              "saturday_close": 1320,
              "updated_at": "2018-10-09T14:16:02.638Z",
              "quantity": 0,
              "updated_on": "2018-09-06",
              "store_no": 38
          },
          {
              "id": 187,
              "is_dead": false,
              "name": "Bayfield & Hanmer",
              "tags": "bayfield hanmer 534 street barrie l4m5a2",
              "address_line_1": "534 Bayfield Street",
              "address_line_2": null,
              "city": "Barrie",
              "postal_code": "L4M5A2",
              "telephone": "(705) 722-1046",
              "fax": "(705) 722-0854",
              "latitude": 44.4145,
              "longitude": -79.7132,
              "products_count": 4578,
              "inventory_count": 102873,
              "inventory_price_in_cents": 190181184,
              "inventory_volume_in_milliliters": 80955513,
              "has_wheelchair_accessability": true,
              "has_bilingual_services": false,
              "has_product_consultant": true,
              "has_tasting_bar": true,
              "has_beer_cold_room": true,
              "has_special_occasion_permits": false,
              "has_vintages_corner": true,
              "has_parking": true,
              "has_transit_access": true,
              "sunday_open": 660,
              "sunday_close": 1080,
              "monday_open": 600,
              "monday_close": 1320,
              "tuesday_open": 600,
              "tuesday_close": 1320,
              "wednesday_open": 600,
              "wednesday_close": 1320,
              "thursday_open": 600,
              "thursday_close": 1320,
              "friday_open": 600,
              "friday_close": 1320,
              "saturday_open": 600,
              "saturday_close": 1320,
              "updated_at": "2018-10-09T14:15:35.659Z",
              "quantity": 0,
              "updated_on": "2018-09-07",
              "store_no": 187
          },
          {
              "id": 164,
              "is_dead": false,
              "name": "Eglinton & Laird",
              "tags": "eglinton laird 65 wicksteed avenue toronto central toronto-central torontocentral m4g4h9",
              "address_line_1": "65 Wicksteed Avenue",
              "address_line_2": null,
              "city": "Toronto",
              "postal_code": "M4G4H9",
              "telephone": "(416) 425-6282",
              "fax": "(416) 425-6151",
              "latitude": 43.7097,
              "longitude": -79.36,
              "products_count": 4221,
              "inventory_count": 103910,
              "inventory_price_in_cents": 205521932,
              "inventory_volume_in_milliliters": 78750054,
              "has_wheelchair_accessability": true,
              "has_bilingual_services": true,
              "has_product_consultant": true,
              "has_tasting_bar": false,
              "has_beer_cold_room": true,
              "has_special_occasion_permits": false,
              "has_vintages_corner": true,
              "has_parking": true,
              "has_transit_access": true,
              "sunday_open": 660,
              "sunday_close": 1080,
              "monday_open": 540,
              "monday_close": 1260,
              "tuesday_open": 540,
              "tuesday_close": 1260,
              "wednesday_open": 540,
              "wednesday_close": 1260,
              "thursday_open": 540,
              "thursday_close": 1260,
              "friday_open": 540,
              "friday_close": 1260,
              "saturday_open": 540,
              "saturday_close": 1260,
              "updated_at": "2018-10-09T14:15:19.015Z",
              "quantity": 0,
              "updated_on": "2018-09-14",
              "store_no": 164
          },
          {
              "id": 624,
              "is_dead": false,
              "name": "Innes & Tenth Line",
              "tags": "innes tenth line 4220 rd unit #1 building f ottawa orleans ottawa-orleans ottawaorleans k4a5e6",
              "address_line_1": "4220 Innes Rd",
              "address_line_2": "Unit #1 Building F",
              "city": "Orleans",
              "postal_code": "K4A5E6",
              "telephone": "(613) 837-5527",
              "fax": "(613) 837-7026",
              "latitude": 45.456,
              "longitude": -75.4965,
              "products_count": 3705,
              "inventory_count": 99693,
              "inventory_price_in_cents": 151339241,
              "inventory_volume_in_milliliters": 75553543,
              "has_wheelchair_accessability": true,
              "has_bilingual_services": true,
              "has_product_consultant": true,
              "has_tasting_bar": true,
              "has_beer_cold_room": false,
              "has_special_occasion_permits": false,
              "has_vintages_corner": true,
              "has_parking": true,
              "has_transit_access": true,
              "sunday_open": 660,
              "sunday_close": 1080,
              "monday_open": 570,
              "monday_close": 1260,
              "tuesday_open": 570,
              "tuesday_close": 1260,
              "wednesday_open": 570,
              "wednesday_close": 1260,
              "thursday_open": 570,
              "thursday_close": 1320,
              "friday_open": 570,
              "friday_close": 1320,
              "saturday_open": 570,
              "saturday_close": 1320,
              "updated_at": "2018-10-09T14:16:03.777Z",
              "quantity": 0,
              "updated_on": "2017-10-10",
              "store_no": 624
          },
          {
              "id": 31,
              "is_dead": false,
              "name": "First & Pine",
              "tags": "first pine 1 street collingwood l9y1a1",
              "address_line_1": "1 First Street",
              "address_line_2": null,
              "city": "Collingwood",
              "postal_code": "L9Y1A1",
              "telephone": "(705) 445-3341",
              "fax": "(705) 445-9945",
              "latitude": 44.5028,
              "longitude": -80.2182,
              "products_count": 3668,
              "inventory_count": 97539,
              "inventory_price_in_cents": 160232357,
              "inventory_volume_in_milliliters": 74278896,
              "has_wheelchair_accessability": true,
              "has_bilingual_services": false,
              "has_product_consultant": true,
              "has_tasting_bar": true,
              "has_beer_cold_room": true,
              "has_special_occasion_permits": false,
              "has_vintages_corner": true,
              "has_parking": true,
              "has_transit_access": false,
              "sunday_open": 660,
              "sunday_close": 1080,
              "monday_open": 600,
              "monday_close": 1260,
              "tuesday_open": 600,
              "tuesday_close": 1260,
              "wednesday_open": 600,
              "wednesday_close": 1260,
              "thursday_open": 600,
              "thursday_close": 1260,
              "friday_open": 600,
              "friday_close": 1320,
              "saturday_open": 600,
              "saturday_close": 1320,
              "updated_at": "2018-10-09T14:15:38.873Z",
              "quantity": 0,
              "updated_on": "2018-09-06",
              "store_no": 31
          },
          {
              "id": 149,
              "is_dead": false,
              "name": "Bloor & Royal York",
              "tags": "bloor royal york 2946 street west toronto etobicoke toronto-etobicoke torontoetobicoke m8x1b7",
              "address_line_1": "2946 Bloor Street West",
              "address_line_2": null,
              "city": "Etobicoke",
              "postal_code": "M8X1B7",
              "telephone": "(416) 239-3065",
              "fax": "(416) 239-5266",
              "latitude": 43.6483,
              "longitude": -79.5081,
              "products_count": 4198,
              "inventory_count": 89049,
              "inventory_price_in_cents": 188364567,
              "inventory_volume_in_milliliters": 68455673,
              "has_wheelchair_accessability": false,
              "has_bilingual_services": true,
              "has_product_consultant": true,
              "has_tasting_bar": true,
              "has_beer_cold_room": false,
              "has_special_occasion_permits": false,
              "has_vintages_corner": true,
              "has_parking": false,
              "has_transit_access": true,
              "sunday_open": 570,
              "sunday_close": 1080,
              "monday_open": 600,
              "monday_close": 1260,
              "tuesday_open": 600,
              "tuesday_close": 1260,
              "wednesday_open": 600,
              "wednesday_close": 1260,
              "thursday_open": 600,
              "thursday_close": 1260,
              "friday_open": 600,
              "friday_close": 1260,
              "saturday_open": 600,
              "saturday_close": 1260,
              "updated_at": "2018-10-09T14:15:17.372Z",
              "quantity": 0,
              "updated_on": "2017-10-08",
              "store_no": 149
          },
          {
              "id": 417,
              "is_dead": false,
              "name": "King North & Northfield",
              "tags": "king north northfield 571 street waterloo n2l5z7",
              "address_line_1": "571 King Street North",
              "address_line_2": null,
              "city": "Waterloo",
              "postal_code": "N2L5Z7",
              "telephone": "(519) 884-8511",
              "fax": "(519) 884-5101",
              "latitude": 43.5011,
              "longitude": -80.5339,
              "products_count": 3590,
              "inventory_count": 86599,
              "inventory_price_in_cents": 130711735,
              "inventory_volume_in_milliliters": 68247891,
              "has_wheelchair_accessability": true,
              "has_bilingual_services": false,
              "has_product_consultant": true,
              "has_tasting_bar": false,
              "has_beer_cold_room": false,
              "has_special_occasion_permits": false,
              "has_vintages_corner": true,
              "has_parking": true,
              "has_transit_access": true,
              "sunday_open": 660,
              "sunday_close": 1080,
              "monday_open": 600,
              "monday_close": 1320,
              "tuesday_open": 600,
              "tuesday_close": 1320,
              "wednesday_open": 600,
              "wednesday_close": 1320,
              "thursday_open": 600,
              "thursday_close": 1320,
              "friday_open": 600,
              "friday_close": 1320,
              "saturday_open": 600,
              "saturday_close": 1320,
              "updated_at": "2018-10-09T14:15:36.249Z",
              "quantity": 0,
              "updated_on": "2018-09-07",
              "store_no": 417
          },
          {
              "id": 329,
              "is_dead": false,
              "name": "Steeles & Hwy 410",
              "tags": "steeles hwy 410 545 ave e brampton l6w4s2",
              "address_line_1": "545 Steeles Ave. E.",
              "address_line_2": null,
              "city": "Brampton",
              "postal_code": "L6W4S2",
              "telephone": "(905) 454-7980",
              "fax": "(905) 454-6506",
              "latitude": 43.6779,
              "longitude": -79.7194,
              "products_count": 3365,
              "inventory_count": 84076,
              "inventory_price_in_cents": 138156557,
              "inventory_volume_in_milliliters": 65802058,
              "has_wheelchair_accessability": false,
              "has_bilingual_services": true,
              "has_product_consultant": true,
              "has_tasting_bar": true,
              "has_beer_cold_room": true,
              "has_special_occasion_permits": false,
              "has_vintages_corner": true,
              "has_parking": true,
              "has_transit_access": true,
              "sunday_open": 660,
              "sunday_close": 1080,
              "monday_open": 570,
              "monday_close": 1320,
              "tuesday_open": 570,
              "tuesday_close": 1320,
              "wednesday_open": 570,
              "wednesday_close": 1320,
              "thursday_open": 570,
              "thursday_close": 1320,
              "friday_open": 570,
              "friday_close": 1320,
              "saturday_open": 570,
              "saturday_close": 1320,
              "updated_at": "2018-10-09T14:15:23.190Z",
              "quantity": 0,
              "updated_on": "2017-07-21",
              "store_no": 329
          },
          {
              "id": 776,
              "is_dead": false,
              "name": "Brock & Kingston",
              "tags": "brock kingston 1899 rd unit k3 pickering l1v4h7",
              "address_line_1": "1899 Brock Rd Unit K3",
              "address_line_2": null,
              "city": "Pickering",
              "postal_code": "L1V4H7",
              "telephone": "(905) 427-9830",
              "fax": "(905) 427-9832",
              "latitude": 43.8456,
              "longitude": -79.0727,
              "products_count": 3773,
              "inventory_count": 82322,
              "inventory_price_in_cents": 138744982,
              "inventory_volume_in_milliliters": 65603173,
              "has_wheelchair_accessability": true,
              "has_bilingual_services": false,
              "has_product_consultant": true,
              "has_tasting_bar": false,
              "has_beer_cold_room": false,
              "has_special_occasion_permits": false,
              "has_vintages_corner": true,
              "has_parking": false,
              "has_transit_access": false,
              "sunday_open": 570,
              "sunday_close": 1200,
              "monday_open": 570,
              "monday_close": 1260,
              "tuesday_open": 570,
              "tuesday_close": 1260,
              "wednesday_open": 570,
              "wednesday_close": 1260,
              "thursday_open": 570,
              "thursday_close": 1320,
              "friday_open": 570,
              "friday_close": 1320,
              "saturday_open": 570,
              "saturday_close": 1320,
              "updated_at": "2018-10-09T14:15:26.440Z",
              "quantity": 0,
              "updated_on": "2018-08-23",
              "store_no": 776
          },
          {
              "id": 115,
              "is_dead": false,
              "name": "King S. & William",
              "tags": "king s william 115 street south waterloo n2j5a3",
              "address_line_1": "115 King Street South",
              "address_line_2": null,
              "city": "Waterloo",
              "postal_code": "N2J5A3",
              "telephone": "(519) 886-4970",
              "fax": "(519) 886-1572",
              "latitude": 43.462,
              "longitude": -80.5218,
              "products_count": 3624,
              "inventory_count": 87325,
              "inventory_price_in_cents": 129190036,
              "inventory_volume_in_milliliters": 65022592,
              "has_wheelchair_accessability": true,
              "has_bilingual_services": false,
              "has_product_consultant": true,
              "has_tasting_bar": false,
              "has_beer_cold_room": false,
              "has_special_occasion_permits": false,
              "has_vintages_corner": true,
              "has_parking": true,
              "has_transit_access": true,
              "sunday_open": 660,
              "sunday_close": 1080,
              "monday_open": 600,
              "monday_close": 1320,
              "tuesday_open": 600,
              "tuesday_close": 1320,
              "wednesday_open": 600,
              "wednesday_close": 1320,
              "thursday_open": 600,
              "thursday_close": 1320,
              "friday_open": 600,
              "friday_close": 1320,
              "saturday_open": 600,
              "saturday_close": 1320,
              "updated_at": "2018-10-09T14:15:36.327Z",
              "quantity": 0,
              "updated_on": "2018-09-21",
              "store_no": 115
          },
          {
              "id": 367,
              "is_dead": false,
              "name": "Howard & E.C. Row Expwy",
              "tags": "howard ec row expwy 3165 avenue the roundhouse centre windsor n8x3y9",
              "address_line_1": "3165 Howard Avenue",
              "address_line_2": "The Roundhouse Centre",
              "city": "Windsor",
              "postal_code": "N8X3Y9",
              "telephone": "(519) 972-1772",
              "fax": "(519) 250-1206",
              "latitude": 42.2742,
              "longitude": -83.0058,
              "products_count": 3950,
              "inventory_count": 82539,
              "inventory_price_in_cents": 148897976,
              "inventory_volume_in_milliliters": 63410128,
              "has_wheelchair_accessability": true,
              "has_bilingual_services": true,
              "has_product_consultant": true,
              "has_tasting_bar": true,
              "has_beer_cold_room": false,
              "has_special_occasion_permits": false,
              "has_vintages_corner": true,
              "has_parking": true,
              "has_transit_access": true,
              "sunday_open": 660,
              "sunday_close": 1080,
              "monday_open": 600,
              "monday_close": 1320,
              "tuesday_open": 600,
              "tuesday_close": 1320,
              "wednesday_open": 600,
              "wednesday_close": 1320,
              "thursday_open": 600,
              "thursday_close": 1320,
              "friday_open": 600,
              "friday_close": 1320,
              "saturday_open": 600,
              "saturday_close": 1320,
              "updated_at": "2018-10-09T14:15:58.471Z",
              "quantity": 0,
              "updated_on": "2018-01-26",
              "store_no": 367
          },
          {
              "id": 378,
              "is_dead": false,
              "name": "Gibb & Stevenson",
              "tags": "gibb stevenson 400 st oshawa centre l1j0b2",
              "address_line_1": "400 Gibb St.",
              "address_line_2": "Oshawa Centre",
              "city": "Oshawa",
              "postal_code": "L1J0B2",
              "telephone": "(905) 723-5721",
              "fax": "(905) 723-9703",
              "latitude": 43.8873,
              "longitude": -78.8758,
              "products_count": 3512,
              "inventory_count": 78713,
              "inventory_price_in_cents": 123404442,
              "inventory_volume_in_milliliters": 63013619,
              "has_wheelchair_accessability": true,
              "has_bilingual_services": false,
              "has_product_consultant": true,
              "has_tasting_bar": false,
              "has_beer_cold_room": false,
              "has_special_occasion_permits": false,
              "has_vintages_corner": true,
              "has_parking": true,
              "has_transit_access": true,
              "sunday_open": 570,
              "sunday_close": 1200,
              "monday_open": 570,
              "monday_close": 1260,
              "tuesday_open": 570,
              "tuesday_close": 1260,
              "wednesday_open": 570,
              "wednesday_close": 1260,
              "thursday_open": 570,
              "thursday_close": 1320,
              "friday_open": 570,
              "friday_close": 1320,
              "saturday_open": 570,
              "saturday_close": 1320,
              "updated_at": "2018-10-09T14:15:29.221Z",
              "quantity": 0,
              "updated_on": "2018-10-04",
              "store_no": 378
          },
          {
              "id": 445,
              "is_dead": false,
              "name": "Dundas & Trafalgar",
              "tags": "dundas trafalgar 251 oak walk dr oakville l6h6m3",
              "address_line_1": "251 Oak Walk Dr.",
              "address_line_2": null,
              "city": "Oakville",
              "postal_code": "L6H6M3",
              "telephone": "(905) 257-6300",
              "fax": "(905) 257-6303",
              "latitude": 43.4851,
              "longitude": -79.7199,
              "products_count": 3312,
              "inventory_count": 78307,
              "inventory_price_in_cents": 134566755,
              "inventory_volume_in_milliliters": 62524435,
              "has_wheelchair_accessability": true,
              "has_bilingual_services": false,
              "has_product_consultant": true,
              "has_tasting_bar": false,
              "has_beer_cold_room": false,
              "has_special_occasion_permits": false,
              "has_vintages_corner": true,
              "has_parking": true,
              "has_transit_access": true,
              "sunday_open": 660,
              "sunday_close": 1080,
              "monday_open": 540,
              "monday_close": 1320,
              "tuesday_open": 540,
              "tuesday_close": 1320,
              "wednesday_open": 540,
              "wednesday_close": 1320,
              "thursday_open": 540,
              "thursday_close": 1320,
              "friday_open": 540,
              "friday_close": 1320,
              "saturday_open": 540,
              "saturday_close": 1320,
              "updated_at": "2018-10-09T14:15:25.365Z",
              "quantity": 0,
              "updated_on": "2018-08-29",
              "store_no": 445
          },
          {
              "id": 486,
              "is_dead": false,
              "name": "Cornwall & Trafalgar",
              "tags": "cornwall trafalgar 321 road unit c120 oakville l6j7z5",
              "address_line_1": "321 Cornwall Road",
              "address_line_2": "Unit C120",
              "city": "Oakville",
              "postal_code": "L6J7Z5",
              "telephone": "(905) 845-8100",
              "fax": "(905) 845-8140",
              "latitude": 43.4578,
              "longitude": -79.6785,
              "products_count": 3736,
              "inventory_count": 80698,
              "inventory_price_in_cents": 236946876,
              "inventory_volume_in_milliliters": 61855056,
              "has_wheelchair_accessability": false,
              "has_bilingual_services": false,
              "has_product_consultant": true,
              "has_tasting_bar": true,
              "has_beer_cold_room": false,
              "has_special_occasion_permits": false,
              "has_vintages_corner": true,
              "has_parking": false,
              "has_transit_access": true,
              "sunday_open": 660,
              "sunday_close": 1080,
              "monday_open": 540,
              "monday_close": 1260,
              "tuesday_open": 540,
              "tuesday_close": 1260,
              "wednesday_open": 540,
              "wednesday_close": 1260,
              "thursday_open": 540,
              "thursday_close": 1260,
              "friday_open": 540,
              "friday_close": 1260,
              "saturday_open": 540,
              "saturday_close": 1260,
              "updated_at": "2018-10-09T14:15:25.197Z",
              "quantity": 0,
              "updated_on": "2018-06-23",
              "store_no": 486
          },
          {
              "id": 390,
              "is_dead": false,
              "name": "Mccowan & Hwy 7",
              "tags": "mccowan hwy 7 192 bullock drive markham l3p1w2",
              "address_line_1": "192 Bullock Drive",
              "address_line_2": null,
              "city": "Markham",
              "postal_code": "L3P1W2",
              "telephone": "(905) 472-8600",
              "fax": "(905) 472-7997",
              "latitude": 43.8741,
              "longitude": -79.2818,
              "products_count": 3829,
              "inventory_count": 78592,
              "inventory_price_in_cents": 151025888,
              "inventory_volume_in_milliliters": 59819161,
              "has_wheelchair_accessability": true,
              "has_bilingual_services": false,
              "has_product_consultant": true,
              "has_tasting_bar": true,
              "has_beer_cold_room": false,
              "has_special_occasion_permits": false,
              "has_vintages_corner": true,
              "has_parking": true,
              "has_transit_access": true,
              "sunday_open": 660,
              "sunday_close": 1080,
              "monday_open": 600,
              "monday_close": 1320,
              "tuesday_open": 600,
              "tuesday_close": 1320,
              "wednesday_open": 600,
              "wednesday_close": 1320,
              "thursday_open": 600,
              "thursday_close": 1320,
              "friday_open": 600,
              "friday_close": 1320,
              "saturday_open": 570,
              "saturday_close": 1320,
              "updated_at": "2018-10-09T14:15:24.804Z",
              "quantity": 0,
              "updated_on": "2018-10-05",
              "store_no": 390
          },
          {
              "id": 360,
              "is_dead": false,
              "name": "Wilson & Dufferin",
              "tags": "wilson dufferin 675 avenue toronto north toronto-north torontonorth york m3k1e3",
              "address_line_1": "675 Wilson Avenue",
              "address_line_2": null,
              "city": "North York",
              "postal_code": "M3K1E3",
              "telephone": "(416) 636-5349",
              "fax": "(416) 636-7253",
              "latitude": 43.7327,
              "longitude": -79.4547,
              "products_count": 3204,
              "inventory_count": 81184,
              "inventory_price_in_cents": 116580690,
              "inventory_volume_in_milliliters": 59564431,
              "has_wheelchair_accessability": true,
              "has_bilingual_services": true,
              "has_product_consultant": true,
              "has_tasting_bar": false,
              "has_beer_cold_room": true,
              "has_special_occasion_permits": false,
              "has_vintages_corner": true,
              "has_parking": true,
              "has_transit_access": true,
              "sunday_open": 660,
              "sunday_close": 1080,
              "monday_open": 600,
              "monday_close": 1260,
              "tuesday_open": 600,
              "tuesday_close": 1260,
              "wednesday_open": 600,
              "wednesday_close": 1260,
              "thursday_open": 600,
              "thursday_close": 1260,
              "friday_open": 600,
              "friday_close": 1260,
              "saturday_open": 600,
              "saturday_close": 1260,
              "updated_at": "2018-10-09T14:15:18.930Z",
              "quantity": 1,
              "updated_on": "2018-10-07",
              "store_no": 360
          },
          {
              "id": 263,
              "is_dead": false,
              "name": "Hwy 2 & Waverly Rd",
              "tags": "hwy 2 waverly rd 2344 highway #2 bowmanville l1c0k5",
              "address_line_1": "2344 Highway #2",
              "address_line_2": null,
              "city": "Bowmanville",
              "postal_code": "L1C0K5",
              "telephone": "(905) 623-2391",
              "fax": "(905) 623-2870",
              "latitude": 43.9075,
              "longitude": -78.7102,
              "products_count": 3190,
              "inventory_count": 70437,
              "inventory_price_in_cents": 110809941,
              "inventory_volume_in_milliliters": 59138140,
              "has_wheelchair_accessability": true,
              "has_bilingual_services": false,
              "has_product_consultant": true,
              "has_tasting_bar": true,
              "has_beer_cold_room": true,
              "has_special_occasion_permits": false,
              "has_vintages_corner": true,
              "has_parking": true,
              "has_transit_access": true,
              "sunday_open": 570,
              "sunday_close": 1200,
              "monday_open": 570,
              "monday_close": 1260,
              "tuesday_open": 570,
              "tuesday_close": 1260,
              "wednesday_open": 570,
              "wednesday_close": 1260,
              "thursday_open": 570,
              "thursday_close": 1320,
              "friday_open": 570,
              "friday_close": 1320,
              "saturday_open": 570,
              "saturday_close": 1320,
              "updated_at": "2018-10-09T14:15:32.313Z",
              "quantity": 0,
              "updated_on": "2017-07-29",
              "store_no": 263
          }
      ]
    }
  }

  componentDidMount() {

    // does not currently do anything
    // need results returned from http://lcboapi.com/products/?q=beau%27s+all+natural+brewing
    // CORS error
    // I have hard coded the intended results to the products const

    fetch(PRODUCTS_URL, HEADERS)
      .then(results => {
        return results.json();
      }).then( data => {
        console.log("fetched data.result", data.result);

        data.result
          .filter(product => product.is_seasonal && product.producer_name === "Beau's All Natural Brewing")
          .map((product) =>
            this.setState({
              /*
              products: [
                product,
                ...products
              ]
              */
            }));
      }).catch(function(error) {
        console.log(error)
      });
  }

  // TO DO refactor for both fetch functionality, when api fetch works

  fetchStoresData = (url) => {
    fetch(url, HEADERS)
    .then(results => {
      return results.json();
    }).then( data => {
      console.log("fetched stores data.result", data.result);
      this.setState({ availableStores: data.result})
    }).catch(function(error) {
      console.log(error)
    });
  }

  getFullStoresUrl = id => STORES_URL + id;

  handleSelectProduct = id => {
    this.fetchStoresData(this.getFullStoresUrl());
    this.setState({
      selectedProduct: products.find((product) => product.id === id)
    });
  }

  render() {
    return (
      <div className="App">
        <header className="App-header">
          <h1>Beau's Seasonal Beer</h1>
          <p>
            Since 2006 Beau’s All Natural has been brewing interesting, tasty beers like our Lug Tread Lagered Ale using the best ingredients & local spring water. Our family takes pride in creating unique, wonderful and certified organic craft beer, conceived with honest consideration for the environment and our local communities, and delivered with a sense of friendly relationship. We are an award-winning, local, family-run, organic, and independent brewery.
          </p>
        </header>
        <main>
          <ProductList
            products={products}
            handleSelectProduct={this.handleSelectProduct} />
          <SelectedProduct
            selectedProduct={this.state.selectedProduct}
            availableStores={this.state.availableStoresHardCoded} />
        </main>
      </div>
    );
  }
}

export default App;
