import React, { Component } from 'react';
// import logo from './logo.svg';
import './App.css';
import ProductList from './ProductList';
import SelectedProduct from './SelectedProduct';


/*
const ACCESS_KEY = 'MDo0NTllYzdlYy1jNzc0LTExZTgtYTc1YS1jN2NjNTYwZWNhOTA6WGEzSDdhS2xqbW1wc05ERjE1MFBZMUg2Ykw5SUpnMEpDMEFl';
const URL = 'http://lcboapi.com/products/?q=beau%27s+all+natural+brewing';

const headers = new Headers({
   'Access-Control-Allow-Origin': '*',
   'Authorization': 'Token token='+ ACCESS_KEY,
   'Content-Type': 'application/json'
});

const myInit = {
  header: headers
};
*/

// this const is the data returned from http://lcboapi.com/products/?q=beau%27s+all+natural+brewing
// CORS error
const dataset = {
    "status": 200,
    "message": null,
    "pager": {
        "records_per_page": 20,
        "total_record_count": 27,
        "current_page_record_count": 20,
        "is_first_page": true,
        "is_final_page": false,
        "current_page": 1,
        "current_page_path": "/products?q=beau%27s+all+natural+brewing&page=1",
        "next_page": 2,
        "next_page_path": "/products?q=beau%27s+all+natural+brewing&page=2",
        "previous_page": null,
        "previous_page_path": null,
        "total_pages": 2,
        "total_pages_path": "/products?q=beau%27s+all+natural+brewing&page=2"
    },
    "result": [
        {
            "id": 169334,
            "is_dead": false,
            "name": "Beau's Lug Tread Lagered Ale",
            "tags": "beau's beaus lug tread lagered ale beer hybrid canada ontario all natural brewing bottle",
            "is_discontinued": false,
            "price_in_cents": 1695,
            "regular_price_in_cents": 1695,
            "limited_time_offer_savings_in_cents": 0,
            "limited_time_offer_ends_on": null,
            "bonus_reward_miles": 0,
            "bonus_reward_miles_ends_on": null,
            "stock_type": "LCBO",
            "primary_category": "Beer",
            "secondary_category": "Hybrid",
            "origin": "Canada, Ontario",
            "package": "4x600 mL bottle",
            "package_unit_type": "bottle",
            "package_unit_volume_in_milliliters": 600,
            "total_package_units": 4,
            "volume_in_milliliters": 2400,
            "alcohol_content": 520,
            "price_per_liter_of_alcohol_in_cents": 1358,
            "price_per_liter_in_cents": 706,
            "inventory_count": 10315,
            "inventory_volume_in_milliliters": 24756000,
            "inventory_price_in_cents": 17483925,
            "sugar_content": null,
            "producer_name": "Beau's All Natural Brewing",
            "released_on": "2012-05-11",
            "has_value_added_promotion": false,
            "has_limited_time_offer": false,
            "has_bonus_reward_miles": false,
            "is_seasonal": false,
            "is_vqa": false,
            "is_ocb": true,
            "is_kosher": false,
            "value_added_promotion_description": null,
            "description": null,
            "serving_suggestion": null,
            "tasting_note": "Golden yellow colour with a thick head; aromas of fragant hops, citrus and roasted malt with yeasty tones; dryish, medium bodied, fresh, smooth and creamy, with forward hop and grain/cereal flavours; crisp and refreshing on the finish.",
            "updated_at": "2018-10-04T14:18:22.168Z",
            "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/169334/images/thumb.png",
            "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/169334/images/full.jpeg",
            "varietal": "Kolsch",
            "style": "Medium & Malty",
            "tertiary_category": "Pale Hybrid Beer",
            "sugar_in_grams_per_liter": null,
            "clearance_sale_savings_in_cents": 0,
            "has_clearance_sale": false,
            "product_no": 169334
        },
        {
            "id": 517797,
            "is_dead": false,
            "name": "Beau's Lug Tread",
            "tags": "beau's beaus lug tread beer hybrid canada ontario all natural brewing can",
            "is_discontinued": false,
            "price_in_cents": 994,
            "regular_price_in_cents": 994,
            "limited_time_offer_savings_in_cents": 0,
            "limited_time_offer_ends_on": null,
            "bonus_reward_miles": 0,
            "bonus_reward_miles_ends_on": null,
            "stock_type": "LCBO",
            "primary_category": "Beer",
            "secondary_category": "Hybrid",
            "origin": "Canada, Ontario",
            "package": "4x355 mL can",
            "package_unit_type": "can",
            "package_unit_volume_in_milliliters": 355,
            "total_package_units": 4,
            "volume_in_milliliters": 1420,
            "alcohol_content": 520,
            "price_per_liter_of_alcohol_in_cents": 1346,
            "price_per_liter_in_cents": 700,
            "inventory_count": 14681,
            "inventory_volume_in_milliliters": 20847020,
            "inventory_price_in_cents": 14592914,
            "sugar_content": null,
            "producer_name": "Beau's All Natural Brewing",
            "released_on": "2012-05-11",
            "has_value_added_promotion": false,
            "has_limited_time_offer": false,
            "has_bonus_reward_miles": false,
            "is_seasonal": false,
            "is_vqa": false,
            "is_ocb": true,
            "is_kosher": false,
            "value_added_promotion_description": null,
            "description": null,
            "serving_suggestion": null,
            "tasting_note": "Golden yellow colour with a thick head; aromas of fragant hops, citrus and roasted malt with yeasty tones; dryish, medium bodied, fresh, smooth and creamy, with forward hop and grain/cereal flavours; crisp and refreshing on the finish.",
            "updated_at": "2018-10-04T14:18:21.962Z",
            "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/517797/images/thumb.png",
            "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/517797/images/full.jpeg",
            "varietal": "Kolsch",
            "style": null,
            "tertiary_category": "Pale Hybrid Beer",
            "sugar_in_grams_per_liter": null,
            "clearance_sale_savings_in_cents": 0,
            "has_clearance_sale": false,
            "product_no": 517797
        },
        {
            "id": 576926,
            "is_dead": false,
            "name": "Beau's Lug Tread",
            "tags": "beau's beaus lug tread beer hybrid canada ontario all natural brewing can",
            "is_discontinued": false,
            "price_in_cents": 325,
            "regular_price_in_cents": 325,
            "limited_time_offer_savings_in_cents": 0,
            "limited_time_offer_ends_on": null,
            "bonus_reward_miles": 0,
            "bonus_reward_miles_ends_on": null,
            "stock_type": "LCBO",
            "primary_category": "Beer",
            "secondary_category": "Hybrid",
            "origin": "Canada, Ontario",
            "package": "473 mL can",
            "package_unit_type": "can",
            "package_unit_volume_in_milliliters": 473,
            "total_package_units": 1,
            "volume_in_milliliters": 473,
            "alcohol_content": 520,
            "price_per_liter_of_alcohol_in_cents": 1321,
            "price_per_liter_in_cents": 687,
            "inventory_count": 26531,
            "inventory_volume_in_milliliters": 12549163,
            "inventory_price_in_cents": 8622575,
            "sugar_content": null,
            "producer_name": "Beau's All Natural Brewing",
            "released_on": "2012-05-11",
            "has_value_added_promotion": false,
            "has_limited_time_offer": false,
            "has_bonus_reward_miles": false,
            "is_seasonal": false,
            "is_vqa": false,
            "is_ocb": true,
            "is_kosher": false,
            "value_added_promotion_description": null,
            "description": null,
            "serving_suggestion": null,
            "tasting_note": "Golden yellow colour with a thick head; aromas of fragant hops, citrus and roasted malt with yeasty tones; dryish, medium bodied, fresh, smooth and creamy, with forward hop and grain/cereal flavours; crisp and refreshing on the finish.",
            "updated_at": "2018-10-04T14:18:21.709Z",
            "image_thumb_url": null,
            "image_url": null,
            "varietal": "Kolsch",
            "style": "Medium & Malty",
            "tertiary_category": "Pale Hybrid Beer",
            "sugar_in_grams_per_liter": null,
            "clearance_sale_savings_in_cents": 0,
            "has_clearance_sale": false,
            "product_no": 576926
        },
        {
            "id": 575365,
            "is_dead": false,
            "name": "Beau's Full Time IPA",
            "tags": "beau's beaus full time ipa beer ale canada ontario all natural brewing can",
            "is_discontinued": false,
            "price_in_cents": 395,
            "regular_price_in_cents": 395,
            "limited_time_offer_savings_in_cents": 0,
            "limited_time_offer_ends_on": null,
            "bonus_reward_miles": 0,
            "bonus_reward_miles_ends_on": null,
            "stock_type": "LCBO",
            "primary_category": "Beer",
            "secondary_category": "Ale",
            "origin": "Canada, Ontario",
            "package": "473 mL can",
            "package_unit_type": "can",
            "package_unit_volume_in_milliliters": 473,
            "total_package_units": 1,
            "volume_in_milliliters": 473,
            "alcohol_content": 670,
            "price_per_liter_of_alcohol_in_cents": 1246,
            "price_per_liter_in_cents": 835,
            "inventory_count": 18518,
            "inventory_volume_in_milliliters": 8759014,
            "inventory_price_in_cents": 7314610,
            "sugar_content": null,
            "producer_name": "Beau's All Natural Brewing",
            "released_on": "2018-07-03",
            "has_value_added_promotion": false,
            "has_limited_time_offer": false,
            "has_bonus_reward_miles": false,
            "is_seasonal": false,
            "is_vqa": false,
            "is_ocb": true,
            "is_kosher": false,
            "value_added_promotion_description": null,
            "description": null,
            "serving_suggestion": "Serve with Mexican, Thai or Sichuan cuisine.",
            "tasting_note": "The West Coast IPA style is driven by hops, and Full Time delivers with aromas of tropical fruit, citrus and pine. On the palate its medium bodied and creamy in texture, with pronounced fruit flavours, underscored by citrus and sweet malt. Moderate hop bitterness is countered by malt on the lengthy and balanced finish.",
            "updated_at": "2018-10-04T14:18:21.015Z",
            "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/575365/images/thumb.png",
            "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/575365/images/full.jpeg",
            "varietal": "American Pale Ale",
            "style": "Medium & Hoppy",
            "tertiary_category": "India Pale Ale (IPA)",
            "sugar_in_grams_per_liter": null,
            "clearance_sale_savings_in_cents": 0,
            "has_clearance_sale": false,
            "product_no": 575365
        },
        {
            "id": 576868,
            "is_dead": false,
            "name": "Beau's Mix Fall 2018",
            "tags": "beau's beaus mix fall 2018 beer gift and sampler packs canada ontario all natural brewing bottle",
            "is_discontinued": false,
            "price_in_cents": 2195,
            "regular_price_in_cents": 2195,
            "limited_time_offer_savings_in_cents": 0,
            "limited_time_offer_ends_on": null,
            "bonus_reward_miles": 0,
            "bonus_reward_miles_ends_on": null,
            "stock_type": "LCBO",
            "primary_category": "Beer",
            "secondary_category": "Gift and Sampler Packs",
            "origin": "Canada, Ontario",
            "package": "4x600 mL bottle",
            "package_unit_type": "bottle",
            "package_unit_volume_in_milliliters": 600,
            "total_package_units": 4,
            "volume_in_milliliters": 2400,
            "alcohol_content": 500,
            "price_per_liter_of_alcohol_in_cents": 1829,
            "price_per_liter_in_cents": 914,
            "inventory_count": 3347,
            "inventory_volume_in_milliliters": 8032800,
            "inventory_price_in_cents": 7346665,
            "sugar_content": null,
            "producer_name": "Beau's All Natural Brewing",
            "released_on": null,
            "has_value_added_promotion": false,
            "has_limited_time_offer": false,
            "has_bonus_reward_miles": false,
            "is_seasonal": true,
            "is_vqa": false,
            "is_ocb": false,
            "is_kosher": false,
            "value_added_promotion_description": null,
            "description": null,
            "serving_suggestion": null,
            "tasting_note": null,
            "updated_at": "2018-10-04T14:18:22.344Z",
            "image_thumb_url": null,
            "image_url": null,
            "varietal": "Taster Pack",
            "style": null,
            "tertiary_category": "Taster Pack",
            "sugar_in_grams_per_liter": null,
            "clearance_sale_savings_in_cents": 0,
            "has_clearance_sale": false,
            "product_no": 576868
        },
        {
            "id": 436899,
            "is_dead": false,
            "name": "Beau's Farm Table Marzen",
            "tags": "beau's beaus farm table marzen beer lager canada ontario all natural brewing bottle",
            "is_discontinued": false,
            "price_in_cents": 595,
            "regular_price_in_cents": 595,
            "limited_time_offer_savings_in_cents": 0,
            "limited_time_offer_ends_on": null,
            "bonus_reward_miles": 0,
            "bonus_reward_miles_ends_on": null,
            "stock_type": "LCBO",
            "primary_category": "Beer",
            "secondary_category": "Lager",
            "origin": "Canada, Ontario",
            "package": "600 mL bottle",
            "package_unit_type": "bottle",
            "package_unit_volume_in_milliliters": 600,
            "total_package_units": 1,
            "volume_in_milliliters": 600,
            "alcohol_content": 550,
            "price_per_liter_of_alcohol_in_cents": 1803,
            "price_per_liter_in_cents": 991,
            "inventory_count": 3441,
            "inventory_volume_in_milliliters": 2064600,
            "inventory_price_in_cents": 2047395,
            "sugar_content": null,
            "producer_name": "Beau's All Natural Brewing",
            "released_on": "2018-06-27",
            "has_value_added_promotion": false,
            "has_limited_time_offer": false,
            "has_bonus_reward_miles": false,
            "is_seasonal": true,
            "is_vqa": false,
            "is_ocb": true,
            "is_kosher": false,
            "value_added_promotion_description": null,
            "description": null,
            "serving_suggestion": "A great pairing with pork schnitzel, soft pretzels and mustard, beef rouladen.",
            "tasting_note": "Beau's Farm Table Series beers are inspired by classic styles. Märzen is the traditional Oktoberfest style ? malty, biscuity flavours are balanced by an assertive blend of hops, which contribute bitterness and a clean finish. Serve with soft pretzels and plenty of mustard.",
            "updated_at": "2018-10-04T14:18:20.637Z",
            "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/436899/images/thumb.png",
            "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/436899/images/full.jpeg",
            "varietal": "Oktoberfest/Marzen",
            "style": null,
            "tertiary_category": "Amber Lager",
            "sugar_in_grams_per_liter": null,
            "clearance_sale_savings_in_cents": 0,
            "has_clearance_sale": false,
            "product_no": 436899
        },
        {
            "id": 572065,
            "is_dead": false,
            "name": "Beau's B-Side Tagwerk",
            "tags": "beau's beaus b side b-side bside tagwerk beer ale canada ontario all natural brewing bottle",
            "is_discontinued": false,
            "price_in_cents": 595,
            "regular_price_in_cents": 595,
            "limited_time_offer_savings_in_cents": 0,
            "limited_time_offer_ends_on": null,
            "bonus_reward_miles": 0,
            "bonus_reward_miles_ends_on": null,
            "stock_type": "LCBO",
            "primary_category": "Beer",
            "secondary_category": "Ale",
            "origin": "Canada, Ontario",
            "package": "600 mL bottle",
            "package_unit_type": "bottle",
            "package_unit_volume_in_milliliters": 600,
            "total_package_units": 1,
            "volume_in_milliliters": 600,
            "alcohol_content": 690,
            "price_per_liter_of_alcohol_in_cents": 1437,
            "price_per_liter_in_cents": 991,
            "inventory_count": 2970,
            "inventory_volume_in_milliliters": 1782000,
            "inventory_price_in_cents": 1767150,
            "sugar_content": null,
            "producer_name": "Beau's All Natural Brewing",
            "released_on": null,
            "has_value_added_promotion": false,
            "has_limited_time_offer": false,
            "has_bonus_reward_miles": false,
            "is_seasonal": true,
            "is_vqa": false,
            "is_ocb": true,
            "is_kosher": false,
            "value_added_promotion_description": null,
            "description": null,
            "serving_suggestion": null,
            "tasting_note": null,
            "updated_at": "2018-10-04T14:18:19.897Z",
            "image_thumb_url": null,
            "image_url": null,
            "varietal": null,
            "style": null,
            "tertiary_category": null,
            "sugar_in_grams_per_liter": null,
            "clearance_sale_savings_in_cents": 0,
            "has_clearance_sale": false,
            "product_no": 572065
        },
        {
            "id": 539056,
            "is_dead": false,
            "name": "Beau's Tom Green Cherry Milk Stout",
            "tags": "beau's beaus tom green cherry milk stout beer ale canada ontario all natural brewing bottle",
            "is_discontinued": false,
            "price_in_cents": 595,
            "regular_price_in_cents": 595,
            "limited_time_offer_savings_in_cents": 0,
            "limited_time_offer_ends_on": null,
            "bonus_reward_miles": 0,
            "bonus_reward_miles_ends_on": null,
            "stock_type": "LCBO",
            "primary_category": "Beer",
            "secondary_category": "Ale",
            "origin": "Canada, Ontario",
            "package": "600 mL bottle",
            "package_unit_type": "bottle",
            "package_unit_volume_in_milliliters": 600,
            "total_package_units": 1,
            "volume_in_milliliters": 600,
            "alcohol_content": 560,
            "price_per_liter_of_alcohol_in_cents": 1770,
            "price_per_liter_in_cents": 991,
            "inventory_count": 2720,
            "inventory_volume_in_milliliters": 1632000,
            "inventory_price_in_cents": 1618400,
            "sugar_content": null,
            "producer_name": "Beau's All Natural Brewing",
            "released_on": "2018-09-21",
            "has_value_added_promotion": false,
            "has_limited_time_offer": false,
            "has_bonus_reward_miles": false,
            "is_seasonal": true,
            "is_vqa": false,
            "is_ocb": true,
            "is_kosher": false,
            "value_added_promotion_description": null,
            "description": null,
            "serving_suggestion": "Serve chilled with not-too-sweet cherry based desserts or BBQ pork and roast poultry with cherry coulis.",
            "tasting_note": "The latest version of the Tom Green Milk Stout; this one is brewed with added organic cherries. It pours a dark amber brown colour with thick head. Exhibits aromas and flavours of dark cherry jam, malt, coffee and chocolate with toasted pie filling. Palate is medium sweet, smooth and silky with a roast cherry fruit finish.",
            "updated_at": "2018-10-04T14:18:23.171Z",
            "image_thumb_url": null,
            "image_url": null,
            "varietal": "Stout",
            "style": "Medium & Roasted",
            "tertiary_category": "Stout",
            "sugar_in_grams_per_liter": null,
            "clearance_sale_savings_in_cents": 0,
            "has_clearance_sale": false,
            "product_no": 539056
        },
        {
            "id": 538892,
            "is_dead": false,
            "name": "Beau's Three Knocks",
            "tags": "beau's beaus three knocks beer ale canada ontario all natural brewing bottle",
            "is_discontinued": false,
            "price_in_cents": 795,
            "regular_price_in_cents": 795,
            "limited_time_offer_savings_in_cents": 0,
            "limited_time_offer_ends_on": null,
            "bonus_reward_miles": 0,
            "bonus_reward_miles_ends_on": null,
            "stock_type": "LCBO",
            "primary_category": "Beer",
            "secondary_category": "Ale",
            "origin": "Canada, Ontario",
            "package": "600 mL bottle",
            "package_unit_type": "bottle",
            "package_unit_volume_in_milliliters": 600,
            "total_package_units": 1,
            "volume_in_milliliters": 600,
            "alcohol_content": 700,
            "price_per_liter_of_alcohol_in_cents": 1892,
            "price_per_liter_in_cents": 1325,
            "inventory_count": 2691,
            "inventory_volume_in_milliliters": 1614600,
            "inventory_price_in_cents": 2139345,
            "sugar_content": null,
            "producer_name": "Beau's All Natural Brewing",
            "released_on": null,
            "has_value_added_promotion": false,
            "has_limited_time_offer": false,
            "has_bonus_reward_miles": false,
            "is_seasonal": true,
            "is_vqa": false,
            "is_ocb": true,
            "is_kosher": false,
            "value_added_promotion_description": null,
            "description": null,
            "serving_suggestion": null,
            "tasting_note": null,
            "updated_at": "2018-10-04T14:18:23.024Z",
            "image_thumb_url": null,
            "image_url": null,
            "varietal": null,
            "style": null,
            "tertiary_category": null,
            "sugar_in_grams_per_liter": null,
            "clearance_sale_savings_in_cents": 0,
            "has_clearance_sale": false,
            "product_no": 538892
        },
        {
            "id": 625327,
            "is_dead": false,
            "name": "Beau's Four Flower Gruit",
            "tags": "beau's beaus four flower gruit beer ale canada ontario all natural brewing bottle",
            "is_discontinued": false,
            "price_in_cents": 595,
            "regular_price_in_cents": 595,
            "limited_time_offer_savings_in_cents": 0,
            "limited_time_offer_ends_on": null,
            "bonus_reward_miles": 0,
            "bonus_reward_miles_ends_on": null,
            "stock_type": "LCBO",
            "primary_category": "Beer",
            "secondary_category": "Ale",
            "origin": "Canada, Ontario",
            "package": "600 mL bottle",
            "package_unit_type": "bottle",
            "package_unit_volume_in_milliliters": 600,
            "total_package_units": 1,
            "volume_in_milliliters": 600,
            "alcohol_content": 560,
            "price_per_liter_of_alcohol_in_cents": 1770,
            "price_per_liter_in_cents": 991,
            "inventory_count": 2326,
            "inventory_volume_in_milliliters": 1395600,
            "inventory_price_in_cents": 1383970,
            "sugar_content": null,
            "producer_name": "Beau's All Natural Brewing",
            "released_on": "2018-09-21",
            "has_value_added_promotion": false,
            "has_limited_time_offer": false,
            "has_bonus_reward_miles": false,
            "is_seasonal": true,
            "is_vqa": false,
            "is_ocb": false,
            "is_kosher": false,
            "value_added_promotion_description": null,
            "description": null,
            "serving_suggestion": "Serve chilled in a wine glass. Savour on its own or pair with light goat or blue cheeses. Also use to enhance food recipes, including stocks and sauces.",
            "tasting_note": "An inspired version of gruit ale. This batch includes four organic flowers: red clover, elderflower, borage and honeysuckle. It's hazy orange in colour with perfumed floral and fruit aromas. Light and rounded palate, with malty notes and flavours of citrus, herb, red berry and apple. Clean and crisp finish. Serve chilled.",
            "updated_at": "2018-10-04T14:18:20.889Z",
            "image_thumb_url": null,
            "image_url": null,
            "varietal": "Flavoured Beer",
            "style": "Medium & Fruity",
            "tertiary_category": "Flavoured Beer",
            "sugar_in_grams_per_liter": null,
            "clearance_sale_savings_in_cents": 0,
            "has_clearance_sale": false,
            "product_no": 625327
        },
        {
            "id": 560003,
            "is_dead": false,
            "name": "Beau's Summer Mixed Pack",
            "tags": "beau's beaus summer mixed pack beer gift and sampler packs canada ontario all natural brewing bottle",
            "is_discontinued": false,
            "price_in_cents": 2195,
            "regular_price_in_cents": 2195,
            "limited_time_offer_savings_in_cents": 0,
            "limited_time_offer_ends_on": null,
            "bonus_reward_miles": 0,
            "bonus_reward_miles_ends_on": null,
            "stock_type": "LCBO",
            "primary_category": "Beer",
            "secondary_category": "Gift and Sampler Packs",
            "origin": "Canada, Ontario",
            "package": "4x600 mL bottle",
            "package_unit_type": "bottle",
            "package_unit_volume_in_milliliters": 600,
            "total_package_units": 4,
            "volume_in_milliliters": 2400,
            "alcohol_content": 520,
            "price_per_liter_of_alcohol_in_cents": 1758,
            "price_per_liter_in_cents": 914,
            "inventory_count": 442,
            "inventory_volume_in_milliliters": 1060800,
            "inventory_price_in_cents": 970190,
            "sugar_content": null,
            "producer_name": "Beau's All Natural Brewing",
            "released_on": "2018-05-22",
            "has_value_added_promotion": false,
            "has_limited_time_offer": false,
            "has_bonus_reward_miles": false,
            "is_seasonal": true,
            "is_vqa": false,
            "is_ocb": true,
            "is_kosher": false,
            "value_added_promotion_description": null,
            "description": null,
            "serving_suggestion": "Serve up poolside.",
            "tasting_note": "Beau's has a knack for assembling mix packs that embody the season perfectly and this year's summer mix is no exception. Cali Common Saison, Buenos Dias Gruit, Blood Simple Blood Orange Witbier and the classic Lug Tread are perfect companions to warm summer nights.",
            "updated_at": "2018-10-04T14:18:22.763Z",
            "image_thumb_url": null,
            "image_url": null,
            "varietal": "Taster Pack",
            "style": null,
            "tertiary_category": "Taster Pack",
            "sugar_in_grams_per_liter": null,
            "clearance_sale_savings_in_cents": 0,
            "has_clearance_sale": false,
            "product_no": 560003
        },
        {
            "id": 365593,
            "is_dead": false,
            "name": "Beau's B-Side Kissmeyer Nordic Pale Ale",
            "tags": "beau's beaus b side b-side bside kissmeyer nordic pale ale beer canada ontario all natural brewing bottle",
            "is_discontinued": false,
            "price_in_cents": 645,
            "regular_price_in_cents": 645,
            "limited_time_offer_savings_in_cents": 0,
            "limited_time_offer_ends_on": null,
            "bonus_reward_miles": 0,
            "bonus_reward_miles_ends_on": null,
            "stock_type": "LCBO",
            "primary_category": "Beer",
            "secondary_category": "Ale",
            "origin": "Canada, Ontario",
            "package": "600 mL bottle",
            "package_unit_type": "bottle",
            "package_unit_volume_in_milliliters": 600,
            "total_package_units": 1,
            "volume_in_milliliters": 600,
            "alcohol_content": 600,
            "price_per_liter_of_alcohol_in_cents": 1791,
            "price_per_liter_in_cents": 1075,
            "inventory_count": 1503,
            "inventory_volume_in_milliliters": 901800,
            "inventory_price_in_cents": 969435,
            "sugar_content": null,
            "producer_name": "Beau's All Natural Brewing",
            "released_on": "2014-11-05",
            "has_value_added_promotion": false,
            "has_limited_time_offer": false,
            "has_bonus_reward_miles": false,
            "is_seasonal": false,
            "is_vqa": false,
            "is_ocb": true,
            "is_kosher": false,
            "value_added_promotion_description": null,
            "description": null,
            "serving_suggestion": "Serve with herb-crusted pork chops, grilled sausages, fried calamari or pretzels.",
            "tasting_note": "Clear, bright medium amber; on the nose there are pronounced notes of Christmas tree, pineapple, pink grapefruit and spice; on the palate it is dry and full bodied, with flavours of grapefruit, heather, cranberry, pine and bitter dried herb.",
            "updated_at": "2018-10-04T14:18:19.771Z",
            "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/365593/images/thumb.png",
            "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/365593/images/full.jpeg",
            "varietal": "American Pale Ale",
            "style": "Medium & Floral",
            "tertiary_category": "Pale Ale",
            "sugar_in_grams_per_liter": null,
            "clearance_sale_savings_in_cents": 0,
            "has_clearance_sale": false,
            "product_no": 365593
        },
        {
            "id": 576850,
            "is_dead": false,
            "name": "Beau's Farm Table Hopfenlager",
            "tags": "beau's beaus farm table hopfenlager beer lager canada ontario all natural brewing bottle",
            "is_discontinued": false,
            "price_in_cents": 595,
            "regular_price_in_cents": 595,
            "limited_time_offer_savings_in_cents": 0,
            "limited_time_offer_ends_on": null,
            "bonus_reward_miles": 0,
            "bonus_reward_miles_ends_on": null,
            "stock_type": "LCBO",
            "primary_category": "Beer",
            "secondary_category": "Lager",
            "origin": "Canada, Ontario",
            "package": "600 mL bottle",
            "package_unit_type": "bottle",
            "package_unit_volume_in_milliliters": 600,
            "total_package_units": 1,
            "volume_in_milliliters": 600,
            "alcohol_content": 660,
            "price_per_liter_of_alcohol_in_cents": 1502,
            "price_per_liter_in_cents": 991,
            "inventory_count": 1209,
            "inventory_volume_in_milliliters": 725400,
            "inventory_price_in_cents": 719355,
            "sugar_content": null,
            "producer_name": "Beau's All Natural Brewing",
            "released_on": null,
            "has_value_added_promotion": false,
            "has_limited_time_offer": false,
            "has_bonus_reward_miles": false,
            "is_seasonal": true,
            "is_vqa": false,
            "is_ocb": true,
            "is_kosher": false,
            "value_added_promotion_description": null,
            "description": null,
            "serving_suggestion": null,
            "tasting_note": null,
            "updated_at": "2018-10-04T14:18:20.519Z",
            "image_thumb_url": null,
            "image_url": null,
            "varietal": "Pale Lager",
            "style": "Medium & Hoppy",
            "tertiary_category": "Pale Lager",
            "sugar_in_grams_per_liter": null,
            "clearance_sale_savings_in_cents": 0,
            "has_clearance_sale": false,
            "product_no": 576850
        },
        {
            "id": 519959,
            "is_dead": false,
            "name": "Beau's Tom Green Summer Stout",
            "tags": "beau's beaus tom green summer stout beer ale canada ontario all natural brewing bottle",
            "is_discontinued": false,
            "price_in_cents": 595,
            "regular_price_in_cents": 595,
            "limited_time_offer_savings_in_cents": 0,
            "limited_time_offer_ends_on": null,
            "bonus_reward_miles": 0,
            "bonus_reward_miles_ends_on": null,
            "stock_type": "LCBO",
            "primary_category": "Beer",
            "secondary_category": "Ale",
            "origin": "Canada, Ontario",
            "package": "600 mL bottle",
            "package_unit_type": "bottle",
            "package_unit_volume_in_milliliters": 600,
            "total_package_units": 1,
            "volume_in_milliliters": 600,
            "alcohol_content": 500,
            "price_per_liter_of_alcohol_in_cents": 1983,
            "price_per_liter_in_cents": 991,
            "inventory_count": 440,
            "inventory_volume_in_milliliters": 264000,
            "inventory_price_in_cents": 261800,
            "sugar_content": null,
            "producer_name": "Beau's All Natural Brewing",
            "released_on": "2018-07-03",
            "has_value_added_promotion": false,
            "has_limited_time_offer": false,
            "has_bonus_reward_miles": false,
            "is_seasonal": true,
            "is_vqa": false,
            "is_ocb": true,
            "is_kosher": false,
            "value_added_promotion_description": null,
            "description": null,
            "serving_suggestion": "Serve with shellfish, game meats, baked beans, meat pies.",
            "tasting_note": "A blond stout is made by infusing golden ale with the rich aroma and flavours of coffee and cocoa. Enjoy aromas and flavours of freshly brewed light-roast coffee, dark chocolate and spice, with just a hint of sweetness on the finish. Serve with venison, smoky barbecue, creamy clam chowder or blue cheese.",
            "updated_at": "2018-10-04T14:18:23.300Z",
            "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/519959/images/thumb.png",
            "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/519959/images/full.jpeg",
            "varietal": "Stout",
            "style": "Medium & Roasted",
            "tertiary_category": "Stout",
            "sugar_in_grams_per_liter": null,
            "clearance_sale_savings_in_cents": 0,
            "has_clearance_sale": false,
            "product_no": 519959
        },
        {
            "id": 525642,
            "is_dead": false,
            "name": "Beau's Fall Mixed Pack",
            "tags": "beau's beaus fall mixed pack beer gift and sampler packs canada ontario all natural brewing bottle",
            "is_discontinued": false,
            "price_in_cents": 2195,
            "regular_price_in_cents": 2195,
            "limited_time_offer_savings_in_cents": 0,
            "limited_time_offer_ends_on": null,
            "bonus_reward_miles": 0,
            "bonus_reward_miles_ends_on": null,
            "stock_type": "LCBO",
            "primary_category": "Beer",
            "secondary_category": "Gift and Sampler Packs",
            "origin": "Canada, Ontario",
            "package": "4x600 mL bottle",
            "package_unit_type": "bottle",
            "package_unit_volume_in_milliliters": 600,
            "total_package_units": 4,
            "volume_in_milliliters": 2400,
            "alcohol_content": 600,
            "price_per_liter_of_alcohol_in_cents": 1524,
            "price_per_liter_in_cents": 914,
            "inventory_count": 88,
            "inventory_volume_in_milliliters": 211200,
            "inventory_price_in_cents": 193160,
            "sugar_content": null,
            "producer_name": "Beau's All Natural Brewing",
            "released_on": "2017-09-18",
            "has_value_added_promotion": false,
            "has_limited_time_offer": false,
            "has_bonus_reward_miles": false,
            "is_seasonal": true,
            "is_vqa": false,
            "is_ocb": true,
            "is_kosher": false,
            "value_added_promotion_description": null,
            "description": null,
            "serving_suggestion": "Perfect for pot-luck gatherings, a style for every palate.",
            "tasting_note": "The eagerly anticipated Fall Mix pack from Beau's includes Lugtread Lagered Ale, Sargeant Stripes Export Stout, Cranberry Derby Cranberry Oat Ale and Spice Principle Spiced Weissebier. Explore the world of craft beer styles!",
            "updated_at": "2018-10-04T14:18:20.402Z",
            "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/525642/images/thumb.png",
            "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/525642/images/full.jpeg",
            "varietal": "Taster Pack",
            "style": null,
            "tertiary_category": "Taster Pack",
            "sugar_in_grams_per_liter": null,
            "clearance_sale_savings_in_cents": 0,
            "has_clearance_sale": false,
            "product_no": 525642
        },
        {
            "id": 514943,
            "is_dead": false,
            "name": "Beau's Halcyon Barrel House Infinity Mirror Brett IPA",
            "tags": "beau's beaus halcyon barrel house infinity mirror brett ipa beer ale canada ontario all natural brewing bottle",
            "is_discontinued": false,
            "price_in_cents": 994,
            "regular_price_in_cents": 994,
            "limited_time_offer_savings_in_cents": 0,
            "limited_time_offer_ends_on": null,
            "bonus_reward_miles": 0,
            "bonus_reward_miles_ends_on": null,
            "stock_type": "LCBO",
            "primary_category": "Beer",
            "secondary_category": "Ale",
            "origin": "Canada, Ontario",
            "package": "750 mL bottle",
            "package_unit_type": "bottle",
            "package_unit_volume_in_milliliters": 750,
            "total_package_units": 1,
            "volume_in_milliliters": 750,
            "alcohol_content": 650,
            "price_per_liter_of_alcohol_in_cents": 2038,
            "price_per_liter_in_cents": 1325,
            "inventory_count": 264,
            "inventory_volume_in_milliliters": 198000,
            "inventory_price_in_cents": 262416,
            "sugar_content": null,
            "producer_name": "Beau's All Natural Brewing",
            "released_on": "2018-07-05",
            "has_value_added_promotion": false,
            "has_limited_time_offer": false,
            "has_bonus_reward_miles": false,
            "is_seasonal": true,
            "is_vqa": false,
            "is_ocb": true,
            "is_kosher": false,
            "value_added_promotion_description": null,
            "description": null,
            "serving_suggestion": "Serve with barbecued pork, mature cheeses or fish with a citrus-based sauce.",
            "tasting_note": "Infinity Mirror is a wild-fermented India pale ale that is aged in red wine barrels. Aromas of grapefruit, baking spice, banana apricot and pineapple. On the palate, it is rich, creamy and frothy with flavours of tangy grapefruit, with banana and toasted nut. Pair with mature cheeses, kimchee or barbecued pork.",
            "updated_at": "2018-10-04T14:18:21.394Z",
            "image_thumb_url": null,
            "image_url": null,
            "varietal": "India Pale Ale (Ipa)",
            "style": "Medium & Hoppy",
            "tertiary_category": "India Pale Ale (IPA)",
            "sugar_in_grams_per_liter": null,
            "clearance_sale_savings_in_cents": 0,
            "has_clearance_sale": false,
            "product_no": 514943
        },
        {
            "id": 546861,
            "is_dead": false,
            "name": "Beau's Halcyon Barrel House Gravity Well",
            "tags": "beau's beaus halcyon barrel house gravity well beer ale canada ontario all natural brewing bottle",
            "is_discontinued": false,
            "price_in_cents": 1695,
            "regular_price_in_cents": 1695,
            "limited_time_offer_savings_in_cents": 0,
            "limited_time_offer_ends_on": null,
            "bonus_reward_miles": 0,
            "bonus_reward_miles_ends_on": null,
            "stock_type": "LCBO",
            "primary_category": "Beer",
            "secondary_category": "Ale",
            "origin": "Canada, Ontario",
            "package": "750 mL bottle",
            "package_unit_type": "bottle",
            "package_unit_volume_in_milliliters": 750,
            "total_package_units": 1,
            "volume_in_milliliters": 750,
            "alcohol_content": 900,
            "price_per_liter_of_alcohol_in_cents": 2511,
            "price_per_liter_in_cents": 2260,
            "inventory_count": 156,
            "inventory_volume_in_milliliters": 117000,
            "inventory_price_in_cents": 264420,
            "sugar_content": null,
            "producer_name": "Beau's All Natural Brewing",
            "released_on": null,
            "has_value_added_promotion": false,
            "has_limited_time_offer": false,
            "has_bonus_reward_miles": false,
            "is_seasonal": true,
            "is_vqa": false,
            "is_ocb": true,
            "is_kosher": false,
            "value_added_promotion_description": null,
            "description": null,
            "serving_suggestion": null,
            "tasting_note": null,
            "updated_at": "2018-10-04T14:18:21.272Z",
            "image_thumb_url": null,
            "image_url": null,
            "varietal": "Sour",
            "style": "Medium & Tart",
            "tertiary_category": "Sour",
            "sugar_in_grams_per_liter": null,
            "clearance_sale_savings_in_cents": 0,
            "has_clearance_sale": false,
            "product_no": 546861
        },
        {
            "id": 589325,
            "is_dead": false,
            "name": "Beau's de Berry's Treasure",
            "tags": "beau's beaus de berry's berrys treasure beer ale canada ontario all natural brewing bottle",
            "is_discontinued": false,
            "price_in_cents": 795,
            "regular_price_in_cents": 795,
            "limited_time_offer_savings_in_cents": 0,
            "limited_time_offer_ends_on": null,
            "bonus_reward_miles": 0,
            "bonus_reward_miles_ends_on": null,
            "stock_type": "LCBO",
            "primary_category": "Beer",
            "secondary_category": "Ale",
            "origin": "Canada, Ontario",
            "package": "600 mL bottle",
            "package_unit_type": "bottle",
            "package_unit_volume_in_milliliters": 600,
            "total_package_units": 1,
            "volume_in_milliliters": 600,
            "alcohol_content": 450,
            "price_per_liter_of_alcohol_in_cents": 2944,
            "price_per_liter_in_cents": 1325,
            "inventory_count": 194,
            "inventory_volume_in_milliliters": 116400,
            "inventory_price_in_cents": 154230,
            "sugar_content": null,
            "producer_name": "Beau's All Natural Brewing",
            "released_on": "2018-07-25",
            "has_value_added_promotion": false,
            "has_limited_time_offer": false,
            "has_bonus_reward_miles": false,
            "is_seasonal": true,
            "is_vqa": false,
            "is_ocb": true,
            "is_kosher": false,
            "value_added_promotion_description": null,
            "description": null,
            "serving_suggestion": null,
            "tasting_note": "Gose is a German-style beer with a characteristic saltiness. This locally produced version of Gose is brewed with added organic black raspberries and rhubarb that enhance the aromas and add a refreshing balanced tanginess to the finish. The palate is medium in body, smooth with light sweetness and toasted grainy notes.",
            "updated_at": "2018-10-04T14:18:20.273Z",
            "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/589325/images/thumb.png",
            "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/589325/images/full.jpeg",
            "varietal": "Sour",
            "style": "Medium & Fruity",
            "tertiary_category": "Sour",
            "sugar_in_grams_per_liter": null,
            "clearance_sale_savings_in_cents": 0,
            "has_clearance_sale": false,
            "product_no": 589325
        },
        {
            "id": 519942,
            "is_dead": false,
            "name": "Beau's Farm Table Saison",
            "tags": "beau's beaus farm table saison beer ale canada ontario all natural brewing bottle",
            "is_discontinued": true,
            "price_in_cents": 595,
            "regular_price_in_cents": 595,
            "limited_time_offer_savings_in_cents": 0,
            "limited_time_offer_ends_on": null,
            "bonus_reward_miles": 0,
            "bonus_reward_miles_ends_on": null,
            "stock_type": "LCBO",
            "primary_category": "Beer",
            "secondary_category": "Ale",
            "origin": "Canada, Ontario",
            "package": "600 mL bottle",
            "package_unit_type": "bottle",
            "package_unit_volume_in_milliliters": 600,
            "total_package_units": 1,
            "volume_in_milliliters": 600,
            "alcohol_content": 470,
            "price_per_liter_of_alcohol_in_cents": 2109,
            "price_per_liter_in_cents": 991,
            "inventory_count": 131,
            "inventory_volume_in_milliliters": 78600,
            "inventory_price_in_cents": 77945,
            "sugar_content": null,
            "producer_name": "Beau's All Natural Brewing",
            "released_on": "2018-07-03",
            "has_value_added_promotion": false,
            "has_limited_time_offer": false,
            "has_bonus_reward_miles": false,
            "is_seasonal": true,
            "is_vqa": false,
            "is_ocb": true,
            "is_kosher": false,
            "value_added_promotion_description": null,
            "description": null,
            "serving_suggestion": "Serve with sausages, mature cheeses or grilled salmon.",
            "tasting_note": "Beau's Farm Table Series is inspired by tradition, and each beer is brewed to a classic style. Saison is a cloudy gold, with aromas of tropical fruit, citrus, spice and piney hops. On the palate, it is balanced, and superbly food-friendly with fruity and savoury notes. Serve with sausages, mature cheeses or grilled salmon.",
            "updated_at": "2018-10-04T14:18:20.759Z",
            "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/519942/images/thumb.png",
            "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/519942/images/full.jpeg",
            "varietal": "Belgian Ale",
            "style": "Medium & Fruity",
            "tertiary_category": "Belgian Ale",
            "sugar_in_grams_per_liter": null,
            "clearance_sale_savings_in_cents": 0,
            "has_clearance_sale": false,
            "product_no": 519942
        },
        {
            "id": 539031,
            "is_dead": false,
            "name": "Beau's Cavalier Bleu",
            "tags": "beau's beaus cavalier bleu beer ale canada ontario all natural brewing bottle",
            "is_discontinued": false,
            "price_in_cents": 795,
            "regular_price_in_cents": 795,
            "limited_time_offer_savings_in_cents": 0,
            "limited_time_offer_ends_on": null,
            "bonus_reward_miles": 0,
            "bonus_reward_miles_ends_on": null,
            "stock_type": "LCBO",
            "primary_category": "Beer",
            "secondary_category": "Ale",
            "origin": "Canada, Ontario",
            "package": "600 mL bottle",
            "package_unit_type": "bottle",
            "package_unit_volume_in_milliliters": 600,
            "total_package_units": 1,
            "volume_in_milliliters": 600,
            "alcohol_content": 600,
            "price_per_liter_of_alcohol_in_cents": 2208,
            "price_per_liter_in_cents": 1325,
            "inventory_count": 91,
            "inventory_volume_in_milliliters": 54600,
            "inventory_price_in_cents": 72345,
            "sugar_content": null,
            "producer_name": "Beau's All Natural Brewing",
            "released_on": "2018-06-29",
            "has_value_added_promotion": false,
            "has_limited_time_offer": false,
            "has_bonus_reward_miles": false,
            "is_seasonal": true,
            "is_vqa": false,
            "is_ocb": true,
            "is_kosher": false,
            "value_added_promotion_description": null,
            "description": null,
            "serving_suggestion": "Serve with venison, duck or lamb.",
            "tasting_note": "Located in Vankleek Hill, south of Hawkesbury, Beau's has been brewing organic beer since 2006. This pale Ale is generously hopped with American and German hop varieties, and infused with organic blueberry juice. Assertive hops, citrus and tangy blueberry flavours lead to a cleansing, pleasingly bitter finish.",
            "updated_at": "2018-10-04T14:18:20.142Z",
            "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/539031/images/thumb.png",
            "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/539031/images/full.jpeg",
            "varietal": "India Pale Ale (Ipa)",
            "style": "Medium & Fruity",
            "tertiary_category": "India Pale Ale (IPA)",
            "sugar_in_grams_per_liter": null,
            "clearance_sale_savings_in_cents": 0,
            "has_clearance_sale": false,
            "product_no": 539031
        }
    ],
    "suggestion": null
}

class App extends Component {
  constructor() {
    super();
    this.state = {
      products: [],
      selectedId: null
    }
  }

  componentDidMount() {
    /*
    //fetch(URL, myInit)
    //fetch('https://lcboapi.com/products?access_key=' + ACCESS_KEY)
    //fetch('https://lcboapi.com/products/?q=beau%27s+all+natural+brewing')
    //fetch('https://lcboapi.com/products/?q=beau%27s+all+natural+brewing?access_key=' + ACCESS_KEY, headers)
    //fetch('https://lcboapi.com/products/?q=beau%27s+all+natural+brewing?access_key=' + ACCESS_KEY)
    //fetch('http://lcboapi.com/products/?q=beau%27s+all+natural+brewing')
    fetch('https://lcboapi.com/products?access_key=' + ACCESS_KEY + '/?q=beau%27s+all+natural+brewing')
      .then(results => {
        console.log(results)
        return results.json();
      }).then( data => {

        let products = data.result.map((product) => {
          return(
            <div key={product.id}>
              {product.name}
            </div>
          )
        })

        this.setState({ products: products})

        console.log("state", this.state.products)
        console.log(data)
      }).catch(function(error) {
        console.log(error)
      });
      */
/*
      dataset.result.map((product) => {
        if(product.is_seasonal){
          this.setState({
            products: [
              {
                id: product.id,
                name: product.name,
              },
              ...this.state.products
            ]
          })
        }
      })
*/

let arr2 = JSON.stringify(dataset.result)
let parsedValues = JSON.parse(arr2);
//let valuesFilters = parsedValues.map((product) => product.is_seasonal && product.producer_name === "Beau's All Natural Brewing"))

console.log("mapData:",arr2);
console.log("values:",parsedValues);


      // TO DO - this is not correct
      // should return filtered data, not formatted li

      let filteredProducts = dataset.result.map((product) => {
        if(product.is_seasonal && product.producer_name === "Beau's All Natural Brewing") {
          return(
            <li
              className="productList__item"
              key={product.id}
              onClick={() => this.selectProduct(product.id)}>
              {product.name}
            </li>
          )
        }
      })

//let filteredProducts = dataset.filter( product => product.is_seasonal);

      this.setState({ products: filteredProducts})

  }

  selectProduct = id => {
    console.log(id)
    this.setState({
      selectedId: id
    });
  }

  render() {
    return (
      <div className="App">
        <header className="App-header">
          <h1>Beau's Seasonal Beer</h1>
        </header>
        <main>
          <p>
            Since 2006 Beau’s All Natural has been brewing interesting, tasty beers like our Lug Tread Lagered Ale using the best ingredients & local spring water. Our family takes pride in creating unique, wonderful and certified organic craft beer, conceived with honest consideration for the environment and our local communities, and delivered with a sense of friendly relationship. We are an award-winning, local, family-run, organic, and independent brewery.
          </p>
          <SelectedProduct
            selectedId={this.state.selectedId} />
          <ProductList
            products={this.state.products}
            selectProduct={this.selectProduct} />
        </main>
      </div>
    );
  }
}

export default App;
